rabbitmq/cluster-operator

internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #183 
* Removed the environment variable which specified a non-default location for the mnesia database mount point
* The mount point for the mnesia persistent volume is now `/var/lib/rabbitmq/mnesia`
We investigated using projection keys to mount both the mnesia database & the erlang cookie, but unfortunately PersistentVolumes are not supported in ProjectionVolumeSources.
Ran unit, integration & system tests.
=> Use default location for mnesia database

Makefile, config/default/base/kustomization.yaml, config/default/overlays/dev/kustomization.yaml, config/default/overlays/helm/kustomization.yaml, config/default/overlays/kind/kustomization.yaml, config/installation/kustomization.yaml, config/installation/overlay/ci/kustomization.yaml, config/samples/overlays/ci/kustomization.yaml
`bases` is a deprecated section of the kustomize API, and is replaced by
`resources` in v2.1.0 onwards. Since we use kustomize 3.X, this moves
our kustomization yamls to the new accepted format.
This also moves our Makefile away from using `kubectl <apply/delete>
-k`, which uses kubectl's older, bundled version of Kustomize v2.0.3
(see [this issue](https://github.com/kubernetes/kubectl/issues/818)).
This closes #67 
Ran unit & integration tests. Also successfully deployed to kind using any make targets that I changed.
=> Remove deprecated `bases` from kustomization files

CONTRIBUTING.md, README.md, charts/rabbitmq/Chart.yaml
- also update helm chart description
This closes #
```
```
```
```
=> Consolidates operator naming in docs

internal/resource/statefulset_test.go
=> Fixes unit tests to reflect mnesia base change

internal/resource/admin_secret_test.go, internal/resource/client_service_test.go, internal/resource/erlang_cookie_test.go, internal/resource/headless_service_test.go, internal/resource/rabbitmq_resource_builder_test.go, internal/resource/statefulset_test.go
- Remove some unnecessary test setup in sts unit tests (per comments from PR: https://github.com/rabbitmq/cluster-operator/pull/175)
- Standardize on variable names for all resource.RabbitmqResourceBuilder types in internal/resource tests; it was called `cluster`, `builder`, or `rmqBuilder` and it was confusing to read. I picked `builder` in the end.
Have run unit and integration tests.
=> Small refactorings for internal/resource

README.md, docs/examples/additionalVolumes/README.md, docs/examples/additionalVolumes/rabbitmq.yaml, docs/proposals/20200310-crd-spec-configurability.md, docs/proposals/implemented/20200310-crd-spec-configurability.md
- related to issue #143 
- README updates about required kubernetes version
- example manifest on deploying with two PVCs using sts override
Should be merged after https://github.com/rabbitmq/cluster-operator/pull/175
=> Add example for statefulSetOverride

config/rbac/role.yaml, controllers/rabbitmqcluster_controller.go
We add RBAC permissions to the operator via generator annotations in rabbitmqcluster_controller.go. The length of the feedback loop for testing which are actually necessary (e.g. build an image, deploy to a registry or kind, run all the tests against it) is long and haphazard. Some roles are required by underlying structures (e.g. the listing and watching functions in the Reflector) so it's not just a question of checking what API calls we make in the Reconcile function. Historically, this has resulted in us over provisioning.
Have deployed to GKE, deployed the sample cluster and checked logs. Then ran the system tests and checked logs. Interestingly system tests pass with no `watch` …
=> Prune unnecessary operator RBAC permissions

internal/resource/statefulset.go, internal/resource/statefulset_test.go
Couples fixes to the current sts override implementation while looking at the code.
- SetControllerReference should be called after override is applied
- Labels and annotations override should be merged not replaced when patching
=> Several fixes to statefulSet Override

docs/examples/import-definitions/README.md, docs/examples/import-definitions/rabbitmq.yaml
This closes #104
- add an example that imports definitions json file at node boot leveraging statefulSet Override, and `additionalConfig`
Exported definitions contains all broker objects, including users and permissions. When importing definitions, the admin user of the cluster will be the one recorded from the definitions file, and not the admin user that the operator generates at rabbitmqcluster creation. I've tried deleting the `users` field from the definitions file when importing, and that resulted in the rabbitmqcluster starting with **no user** at all. This is an interesting side effect that the k8s admin secret is not used when importing definitions, and it would be better if …
=> Add example about import definitions

README.md
This changes the documentation guide links point at rabbitmq.com. In addition, it also mentions repository-local
examples and that the guides are open source.
=> Link to doc guides on rabbitmq.com and local examples

internal/resource/statefulset.go, internal/resource/statefulset_test.go
Updates the StatefulSet Pod template to always contain the prometheus
scrape annotations.
This allows users of the default Prometheus helm chart to automatically
scrape any RabbitMQ Pods created by this CR.
This forms part of #118; there will be accompanying docs changes to the RabbitMQ website.
All of unit, integration & system tests pass.
Also confirmed that deploying the operator with this change causes any existing pods to be teminated & brought back up with the new annotations.
=> Add default annotations to all Pod templates

Makefile, config/default/base/manager_image_patch.yaml, system_tests/system_tests.go
This is related to #211. Some changes in 211 broke the system tests.
Remove reference to PivNet registry for RabbitMQ image in basic system test.
This test is too specific to a specific infrastructure setup. By testing that we template the image pull secret correctly in the StatefulSet it should give the same coverage.
```
```
``` …
```
=> Remove private registry test

Dockerfile
Pinning to a specific SHA no longer makes sense with no OSL process.
This addresses #194 - some work still needs to be done to see if another base image is more suitable.
All of unit, integration & system tests are 💚
=> Bump Dockerfile to latest ubuntu

internal/resource/configmap.go, internal/resource/configmap_test.go
This closes #185 
The `cluster_name` property will be set with value matching the CR name. Before this change, the cluster name was the name of the first node who formed the cluster, which resulted in very long names.
Unit and integration tests 🟢
```
```
Deployed the Operator with this changes, created a 3-node cluster and verified in Management UI that cluster name matches the CR name.
=> Set RabbitMQ cluster name to CR name

charts/operator/values.yaml
We can now default to our public image so that no chart configuration is necessary. Once we merge this, we should also update https://www.rabbitmq.com/kubernetes/operator/install-operator.html to basically say `helm install rabbitmq-operator charts/operator`.
=> use our public image by default

api/v1beta1/rabbitmqcluster_types.go, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, docs/examples/mtls/README.md, docs/examples/mtls/rabbitmq.yaml, docs/examples/tls/README.md
This closes #231, after some website changes.
```
```
```
```
=> Add documentation for TLS & mTLS

charts/rabbitmq/example-configurations.yaml, charts/rabbitmq/expected-template-output, charts/rabbitmq/templates/rabbitmq.yaml
This closes #239 
3 missing properties have been added to the template
```
$ cd cluster-operator/charts/rabbitmq
$ ./test.sh
```
You can also `kubectl apply -f expected-template-output` (or actually use helm).
=> Add `envConfig`, `advancedConfig` and `override` to the helm chart

Dockerfile, go.mod
This closes #194 
Moves the base image from Ubuntu to scratch.
There's a few additional requirements on the image other than just running the binary:
* Access to tzdata - provided by Golang 1.15 with the `-tags timetzdata` flag
* Access to CA certs for TLS - provided by installing on Alpine, then copying over to the manager image
* Running as a specified User, with a UID / GID of 1000 - provided by creating a custom `/etc/passwd` & `/etc/group` file
```
```
You will need to target a k8s cluster and have the operator deployed for …
=> Move base operator image to scratch

cr-example.yaml
Before this commit, when deploying this example on a kind cluster, no pod got created and the stateful set contains the following event:
```
Warning  FailedCreate      103s (x19 over 23m)  statefulset-controller  create Pod example-rabbitmq-server-0 in StatefulSet example-rabbitmq-server failed error: Pod "example-rabbitmq-server-0" is invalid: spec.tolerations[0].operator: Invalid value: "": operator must be Exists when `key` is empty, which means "match all values and all keys"
```
After this commit, deploying works.
=> Remove tolerations

.gitignore, bin/kubectl-rabbitmq
* moved from our internal repo
* new commands: install-cluster-operator, secrets, debug, observe
* small behaviour changes
To test:
1. `export PATH=~/workspace/cluster-operator/bin:$PATH`
2. `kubectl rabbitmq` (it will display help)
You can see a demo here: https://asciinema.org/a/354729
=> kubectl rabbitmq plugin

Makefile, README.md, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, hack/crd-patch.json, hack/patch-crd.sh
This closes #230
Add a workaround to make our crd 1.18 compatible.
There could be a upstream fix coming. However, we are unsure about their timeline, and I decide to add this workaround for now, so that we are not blocked.
I looked at alternatives, like using `sed`. However, I think kubectl patch with jsonpatch is more readable here.
Related k8s issue: https://github.com/kubernetes/kubernetes/issues/91395
`make install` succeeds on a local `1.18` kind cluster
=> Make CRD k8s 1.18 compatible

internal/resource/headless_service.go, internal/resource/headless_service_test.go
As pointed out in #269 this port is used for inter-node communication.
See also
* https://github.com/rabbitmq/diy-kubernetes-examples/commit/62ee5952114f894e490d39a8580b93f515184b4f
* https://www.rabbitmq.com/networking.html#epmd-inet-dist-port-range
=> Add distribution port to headless service

.github/dependabot.yml
This closes #286 
Pins minor versions of controller-runtime dependencies. In particular, pins
k8s.io/api to 0.17.*
k8s.io/api-machinery to 0.17.*
k8s.io/client-go to 0.17.*
github.com/go-logr/logr to 0.1.*
These are controller-runtime dependencies and should not be bumped without bumping controller-runtime. When controller-runtime is bumped, the pinned versions must also be updated.
=> Add minor version pinning to controller-runtime dependencies.

bin/kubectl-rabbitmq
I wanted to use the plugin to run perf test with `--rate 100` but perf-test failed to start with `Parsing failed. Reason: Unrecognized option: --rate 100`. While this change introduces a shellcheck warning, it is actually correct.
=> Fix perf-test argument passing

Makefile, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, config/default/overlays/dev/manager_image_patch.yaml, config/default/overlays/kind/manager_image_patch.yaml
Before this commit, when running `make deploy-dev` or `make deploy-kind` the files `config/default/overlays/dev/manager_image_patch.yaml` and `config/default/overlays/kind/manager_image_patch.yaml` showed local changes.
After this commit the git state won't be dirty anymore.
=> Avoid dirty git state

controllers/rabbitmqcluster_controller.go
Before this PR, many unnecessary lines are logged and events created:
```
2020-09-02T12:41:00.273Z        INFO    rabbitmqcluster-controller      d resource definition-rabbitmq-plugins-conf of Type *v1.ConfigMap
2020-09-02T12:41:00.273Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"RabbitmqCluster","namespace":"default","name":"definition","uid":"72e2f4c4-5002-4eb0-9d4e-e0d34b778000","apiVersion":"rabbitmq.com/v1beta1","resourceVersion":"4909"}, "reason": "Successful", "message": "d resource definition-rabbitmq-plugins-conf of Type *v1.ConfigMap"}
2020-09-02T12:41:00.274Z        INFO    rabbitmqcluster-controller      d resource definition-rabbitmq-server-conf of Type *v1.ConfigMap
2020-09-02T12:41:00.274Z        DEBUG …
```
=> Do not log OperationResultNone

Makefile, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
Before this commit `make manifests` removed the copyright notice from `config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml`.
After this commit, the copyright notice is preserved.
=> Preserve copyright notice

internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #255
Use `rabbitmq-upgrade` commands to check synchronization and quorum status, instead of `rabbitmq-queues` commands.
Timeout is set to the same value as the default for grace period timeout.
Have run unit, integration, and system tests.
=> Use new rabbitmq-upgrade commands in preStop hook

config/rbac/role.yaml, controllers/rabbitmqcluster_controller.go, go.mod, internal/resource/statefulset.go, internal/resource/statefulset_test.go, system_tests/system_tests.go
Fixes #234 
1. Allow `rabbitmq-cluster-operator-role` to update `rabbitmqclusters/finalizers`
2. Do not `BlockOwnerDeletion` for PVCs (as done in https://github.com/elastic/cloud-on-k8s/pull/1891)
3. Change group owner of `/var/lib/rabbitmq/mnesia/` to `999`
https://github.com/ansd/rabbitmq-website/tree/k8s-openshift (need to create PR)
If you don't have an OpenShift cluster available, the easiest way to set one up within a few minutes is [CodeReady Containers](https://developers.redhat.com/products/codeready-containers/overview).
* Download CodeReady Containers
* `crc setup`
*  `crc config set memory 12000` (the default of 8192 MiB is too low to run the RabbitMQ operator and a RabbitMQ cluster instance since there isn't much memory left when starting crc)
* `crc start`
* `eval $(crc …
=> Support OpenShift

.github/workflows/pr.yml, system_tests/system_tests.go
Run unit, integration, helm chart, and system tests tests.
Closes to #270
System tests run against a kind cluster on a GitHub hosted Ubuntu VM.
This would require to add a GitHub secret with the GCP key file for authentication: `gcloud auth activate-service-account [ACCOUNT] --key-file=KEY_FILE`.
This comes with two drawbacks:
1. PRs opened by forks won't be able to access this secret. Therefore, the action wouldn't be able to authenticate with GCP:
> secrets are not passed to the runner when a workflow is triggered from a forked repository
see https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
2. The key-file has JSON format. The same site states:
> avoid creating secrets that contain JSON
When (accidentally) printing that JSON, …
=> Run tests for PRs

controllers/rabbitmqcluster_controller.go, controllers/rabbitmqcluster_controller_test.go, go.sum, internal/resource/configmap.go, internal/resource/rabbitmq_plugins.go, internal/resource/statefulset.go, system_tests/system_tests.go
This closes #304
Exec into pods only if StatefulSet is ready and up to date.
Before this commit, we observed in #304 that the controller tried to exec into pods at the same time as the pods got updated due to a StatefulSet restart resulting in connection errors.
The main change is to not set plugins if
```
sts.Status.ReadyReplicas < desiredReplicas || sts.Status.UpdatedReplicas < desiredReplicas
```
because during a StatefulSet restart, it happened multiple times in #304 that since `sts.Status.ReadyReplicas == desiredReplicas`, the `exec` commands got executed and the connection got interrupted because the pod got updated.
The main finding is that `sts.Status.ReadyReplicas == desiredReplicas` can be `true` although the StatefulSet rolling update is still ongoing:
```
$ while true; do …
```
=> Do not exec into pods during rolling update

README.md, api/v1beta1/rabbitmqcluster_types.go, api/v1beta1/rabbitmqcluster_types_test.go, bin/kubectl-rabbitmq, charts/rabbitmq/Chart.yaml
This closes #319 
Deploy rabbitmq 3.8.8 by default
=> Deploy rabbitmq 3.8.8 by default

.github/ISSUE_TEMPLATE/question.md
This is a follow-up to https://github.com/rabbitmq/cluster-operator/commit/83d50c7a1b733e4914e835bd044afa8dd58c34a1, I thought we should mention `#kubernetes` in our community Slack. It is quite active.
=> Mention community Slack in issue template

api/v1beta1/rabbitmqcluster_types.go, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
This PR has no related issue.
Provides short names `rmq` and `rmqc` as short version of `rabbitmqcluster`. 
The short hand `rc` is already taken by native object `ReplicationController`.
Ever typo'ed `rabbitmqclsuter` or `rabbitqmclsuter`? Me too.
This PR allows to do `kubectl get rmq` or `kubectl get rmqc`. Never typo again!
N/A no behavioural change, no change to how we deploy.
=> Short names for RabbitmqCluster resource

README.md, controllers/rabbitmqcluster_controller_test.go, internal/resource/admin_secret.go, internal/resource/admin_secret_test.go, internal/resource/erlang_cookie.go, internal/resource/statefulset.go, internal/resource/statefulset_test.go
This commit stops the operator configuring the default username and
password for the cluster through environment variables. Instead, these
credentials are configured through `/etc/rabbitmq/conf.d/`. This is for
two reasons:
* RabbitMQ is moving away from configuration via env vars
* The operator should not be coupled to functionality in the entrypoint script in the docker-library/rabbitmq Docker image, as this prevents other RabbitMQ images being used
This effectively removes support for RabbitMQ images pre 3.8.4, where
the ability to configure RabbitMQ via sysctl-style `*.conf` files in
the conf.d directory.
See #340 
Unit, Integration & System tests passed. Also tested on kind with …
=> Configure default user/password through conf.d

docs/proposals/20200806-versioning-release-strategy.md
Updating the KEP to reflect the actual state of the releasing strategy. The release is now an arbitrary decision.
=> Reflect new release frequency in versioning KEP

bin/kubectl-rabbitmq
`rabbitmqctl enable_feature_flags` currently doesn't have a `--all` flag. To make it easier to enable all feature flags after an upgrade, I've added a new command to the `kubectl` plugin.
=> New command to enable all feature flags

.github/workflows/stale.yml
This PR introduces a GitHub Action to auto-mark issues & PRs as stale after periods of inactivity. It also closes issues/PRs that have been stale for further periods of inactivity.
Currently, I have that set at:
90 days to go stale
30 further days to be closed
Currently, this is just set in debug mode, so it will not actually mark issues or PRs yet, but once this is merged & tested (needs to be in the main branch for this to work), we can turn off debug mode & adjust the stale period from 90/30 days.
=> Add automation to auto-mark issues & PRs as stale

.github/workflows/stale.yml
Quick follow-up to #367.
This addresses review feedback I got in Slack, as well as promotes the Action to non-debug mode. I managed to test this locally using https://github.com/nektos/act, which is a pretty awesome tool. I won't tag these (so they don't become un-stale!), but it successfully identified 106, 90 & 12 as stale.
=> Promote 'stale' GitHub action to non-debug mode

bin/kubectl-rabbitmq
Added an option to specify storage class name in kubectl-rabbitmq. This is useful in environments without a default storage class.
Added the `--tls-secret` to the usage output. This option was already implemented, but didn't show in the help output.
No code changes.
Test using `kubectl rabbitmq create bunny --replicas 1 --storage-class <some-storage-class>`, then inspect the `RabbitmqCluster`
resource using `kubectl describe rmq bunny`. Observe the property `.spec.persistence.storageClassName` is set.
=> Option to specify storage class in kubectl-rabbitmq

README.md, internal/resource/statefulset.go, internal/resource/statefulset_test.go
This commit causes nodes to go into maintenance mode before the
controller runtime terminates the rabbitmq-server process on a pod stop.
This allows for a more controlled shutdown of pods in a cluster during
rolling restart, or upgrade.
Using https://github.com/Vanlightly/RabbitTestTool, I was able to show that with
these changes, no data loss, or serious periods of cluster
unavailability, were caused during a rolling restart. However, this is
the case without these changes; I attempted to find a demonstrable case
where this change leads to an improvement in rolling restart
reliability, however was not able to improve this beyond its current
reliability.
I still put this PR forward for review, as the core team recommend that
nodes are put into maintenance mode before being stopped, to …
=> Put nodes into maintenance mode in preStop hook

Makefile, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, go.mod, go.sum, hack/remove-override-descriptions.sh, tools/tools.go
Another approach to keep our property descriptions but remove core type descriptions. Compared to https://github.com/rabbitmq/cluster-operator/pull/379, this uses `yj` instead of `yq` and that way avoids all python-related dependencies.
This closes #369
=> Hacky way to remove override descriptions

controllers/rabbitmqcluster_controller_test.go, internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #361
RabbitMQ configuration files (`rabbitmq.conf`, `advanced.config` and `rabbitmq-env.conf`) are mounted as files,
instead of mounting the directory `/etc/rabbitmq` itself. This is necessary to respect any vendor configuration
that may come in RabbitMQ images.
The plugins file had to move to a different location because it needs to be writable by the rabbitmq process.
Mounting the file from a ConfigMap makes it read-only. The solution is to copy this file to a dedicated empty
dir volume in the init container and pass this volume to rabbitmq container.
Unit and integration tests are passing locally. Modified some unit tests in statefulset to reflect new behaviour.
```
make …
```
=> Mount configurations as projected keys

api/v1beta1/rabbitmqcluster_types.go, api/v1beta1/rabbitmqcluster_types_test.go, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, controllers/rabbitmqcluster_controller.go
This PR uses CRD defaulting ([related KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190426-crd-defaulting.md)) to set defaults for CRD fields. Leveraging CRD schema for defaulting reduces complexity of our code and controller logic. It also means that the operator doesn't need a defaulting admission webhook in the future. WIN!
- Defaults are directly set on CRDs so it preserves the default with new versions of CRD
- Defaults can be set for integer, string, slice, and objects, which covers all types
- CRD defaulting has been a feature that's included in CRD v1. It's not supported for CRD `v1beta1`
- Any kubernetes with CRD v1 will support this feature, which is k8s `1.17` and above
Please ensure you run the unit, integration and system tests before …
=> Use CRD defaulting

api/v1beta1/rabbitmqcluster_types.go, bin/kubectl-rabbitmq, charts/rabbitmq/expected-template-output, charts/rabbitmq/templates/rabbitmq.yaml, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
Before this PR, when `replicas` is not specified, the following error occurs:
```
error: error validating "cr-example.yaml": error validating data: ValidationError(RabbitmqCluster.spec): missing required field "replicas" in com.rabbitmq.v1beta1.RabbitmqCluster.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
After this PR, the error does not occur and the default specified in https://github.com/rabbitmq/cluster-operator/blob/df0c63074f1f865487222bb1e494c03befd7cab7/api/v1beta1/rabbitmqcluster_types.go#L42 gets used.
=> Use default for replicas

.github/workflows/pr.yml, system_tests/system_tests.go, system_tests/utils.go
When system tests are run on GitHub actions, we observed that some of them are very flaky.
This PR increases some timeouts because kind on GitHub-hosted runners can be much slower than GKE where our Concourse system tests run.
I tested this PR on a fork.
Closes #395
=> Make system tests less flaky

api/v1beta1/rabbitmqcluster_types.go, api/v1beta1/rabbitmqcluster_types_test.go, api/v1beta1/zz_generated.deepcopy.go, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, controllers/rabbitmqcluster_controller_test.go, internal/resource/statefulset.go, internal/resource/statefulset_test.go
- directly use the k8s type LocalObjectReference to be alignedwith pod template
This closes #343 
- imagePullSecret to imagePullSecrets
- directly use the k8s type LocalObjectReference to be aligned with pod template
- docs changes are already in rabbitmq-website live because I accidentally pushed the commit without forking: https://github.com/rabbitmq/rabbitmq-website/commit/9e589eef59ec746c32cb9b7d116517c86bfb74a0  😅
Previously:
```yaml
spec:
image: <SOME PRIVATE IMAGE>
imagePullSecret: mygreatsecret
```
with this change
```yaml
spec:
image: <SOME PRIVATE IMAGE>
imagePullSecrets:
- name: mygreatsecret
```
Have run unit, integration, and system tests
=> Change spec.imagePullSecrets to spec.imagePullSecrets

controllers/rabbitmqcluster_controller_test.go
-  the expect assertion on length of imagePullSecrets is in an eventually but not as the returned result, which means that the 3 seconds timeout does not apply and when failed at the first iteration the assertion will just fail. While waiting for the statefulSet to update, this could be very flaky on a bad day
- the assertion itself is also redundant, as "ConsistOf" is an exact matcher so the length is asserted already.
- consistent naming for variable `stsName`
```
```
You will need to target a k8s cluster and have the operator …
=> Remove redundant and wrong assertion

Makefile, controllers/rabbitmqcluster_controller.go, controllers/rabbitmqcluster_controller_test.go, internal/resource/client_service.go, internal/resource/configmap.go, internal/resource/default_user_secret.go, internal/resource/erlang_cookie.go, internal/resource/headless_service.go, internal/resource/rabbitmq_plugins.go, internal/resource/rabbitmq_resource_builder.go, internal/resource/role.go, internal/resource/role_binding.go, internal/resource/service_account.go, internal/resource/statefulset.go
This closes #225 
- adds a timestamped annotation to the server-conf configmap "rabbitmq.com/serverConfUpdatedAt" when the configMap is updated
- controller compares the timestamp of the server-conf configMap and the sts restart timestamp (if exists)
- if the sts restart timestamp is before the server conf timestamp, or if the server-conf has the timestamp, and the sts doesn't, the controller restarts the sts by annotating the podTemplate (how we trigger the sts restart is the same as before)
- randomized specs for unit tests.
- deleted unused method "UpdateRequiresStsRestart()" from all the resource builders; it was used previously in the controller for sts updates.
- added test cases …
=> Configuration updates

api/v1beta1/rabbitmqcluster_types.go, api/v1beta1/rabbitmqcluster_types_test.go, internal/resource/configmap.go, internal/resource/configmap_test.go
This closes #392
**Note to reviewers:** the commits should be squashed before merging
Sets `total_memory_available_override_value` in rabbitmq.conf if there is a memory resource limit.
=> Add rabbit memory limit

internal/resource/configmap.go, internal/resource/configmap_test.go
This closes #412 
- Set disk free space limit to 2GB by default
=> Set disk free space limit to 2GB by default

internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #398
- "topology.kubernetes.io/zone" is a popular label set by kubelet on worker nodes
- "ScheduleAnyways" makes sure that this constraint is treated as a soft requirement, and pods still get scheduled without meeting the requirement
- using hostname as topologyKey is also a valid contraint. However, the official docs recommends not to set multiple contraints if possible to aviod conflicts
Added new test in unit tests to ensure on the templating level. Have run unit, integration, and system tests
=> Set topologySpreadConstraints by default

internal/resource/headless_service.go, internal/resource/headless_service_test.go
This closes #420 
Have run unit and integration tests. System tests should run via github actions.
=> Rename cluster-links to cluster-rpc in headless service.

internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #409
- define a tcp readiness probe
- rabbitmq-diagnostics check_port_connectivity as readiness probe causes context deadline exceeded errors, and pods
could be stuck at terminating for deletion
- reduce PeriodSeconds in readinessProbe to 10 seconds since a tcp probe should be less expansive than running a diagnostics command
See issue: #409 for more details
Have run unit, integration, and system tests
=> Use a tcp readiness probe instead of cli command

internal/resource/configmap.go, internal/resource/configmap_test.go
As reported in https://github.com/rabbitmq/cluster-operator/issues/335 and discussed within the team, these settings are unnecessary.
=> Remove `node_cleanup` configuration

internal/resource/client_service.go, internal/resource/configmap.go, internal/resource/rabbitmq_plugins.go, internal/resource/rabbitmq_resource_builder.go, internal/resource/role.go, internal/resource/service_account.go, internal/resource/statefulset.go
This is a simple copy and paste (no change of functionality) such that all resources have the same
code format in the form of:
```
type Builder struct {...}
NewBuilder() *Builder
Build()
Update()
private methods
```
to easier navigate the resources.
=> Apply same code format for all resources

internal/resource/statefulset.go, internal/resource/statefulset_test.go
For images the contain `rabbitmqadmin` CLI, this PR configures that CLI so that it's ready to be used.
This closes rabbitmq/tanzu-cluster-operator#13
=> Set up `rabbitmqadmin` automatically

system_tests/utils.go
- the test seems rather flaky with the 10 seconds
timeout, see pipeline failures:
https://hush-house.pivotal.io/teams/rabbitmq-for-kubernetes/pipelines/operator/jobs/operator-system-tests/builds/670
https://hush-house.pivotal.io/teams/rabbitmq-for-kubernetes/pipelines/operator/jobs/operator-system-tests/builds/666
- use EventuallyWithOffset because this helper function is called twice in the system tests, and its not obvious which one it's failing
=> Bump timeout in mqtt/stomp system tests

internal/resource/configmap_test.go
This way the tests are not sensitive to whitespace differences since they compare actual config
file with the expected value after formatting using the same method as the actual code
To test, you can add/remove some spaces in `expectedRabbitmqConf` and the tests should still pass.
=> Format expected config file with ini pkg

config/default/base/kustomization.yaml
Removed name prefix in the base kustomization file because the name prefix is already present in the manager kustomization.
Adding the name prefix here is producing double prefixed name for the Operator deployment e.g. rabbitmq-cluster-rabbitmq-cluster-operator.
=> Remove duplicated name prefix

internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #433 
- handle the rabbitmq container envVar list as a special case if it's overwritten by override
- we need to ensure that MY_POD_NAME and MY_POD_NAMESPACE are defined first so other envVars values can reference them
Added additional test about templating at unit. Have run unit and integration tests
=> Ensure MY_POD_NAME and MY_POD_NAMESPACE envVar defined first

controllers/rabbitmqcluster_controller.go, controllers/rabbitmqcluster_controller_test.go, controllers/reconcile_cli.go, controllers/reconcile_cli_test.go, controllers/reconcile_post_deploy.go, controllers/reconcile_post_deploy_test.go, controllers/reconcile_rabbitmq_configurations.go, controllers/suite_test.go, controllers/utils.go, system_tests/system_tests.go, system_tests/utils.go
Closes #414 
**Notes:**
* The controller identifies a new RabbitMQ cluster by the operation result `created` of the StatefulSet.
* A new annotation `rabbitmq.com/createdAt` is added onto the created StatefulSet.
* Once all pods are ready, CLI command `rabbitmqctl enable_feature_flag` is used on the first pod of the StatefulSet to enable all stable and previously disabled feature flags. (In future, we could add feature flag methods to https://github.com/michaelklishin/rabbit-hole/ to not exec into the pod anymore.)
=> Enable all feature flags for new clusters

api/v1beta1/rabbitmqcluster_types.go, api/v1beta1/rabbitmqcluster_types_test.go, bin/kubectl-rabbitmq, charts/rabbitmq/example-configurations.yaml, charts/rabbitmq/expected-template-output, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
This closes #441
- Changed the default RabbitMQ image to use tag `3.8.9-management`
The non-management image variant disables metrics collection by the management agent, resulting in very little information
shown in the management UI. We want to always enable the management UI as it is a common entry point to RabbitMQ
administration. It's also not straightforward to re-enable the metric collection in the non-management variant.
- Made changes to unit tests. Those are passing.
- No changes to integration or system tests. Those are also green.
=> Use RabbitMQ management image variant

.github/workflows/release.yml, hack/rabbitmq.yaml
Since https://github.com/kubernetes-sigs/krew-index/pull/895 is merged, we can now add automation to bump the kubectl rabbitmq plugin on every operator release.
The `hack/rabbitmq.yaml` template is output by https://rajatjindal.com/tools/krew-release-bot-helper/.
Relates #440.
=> Add automation to bump kubectl rabbitmq in krew index

bin/kubectl-rabbitmq, bin/kubectl-rabbitmq.bats
Relates #440.
Since we require the kubectl rabbitmq plugin to be installed via krew, the easiest way to output the plugin version is to ask krew. As explained in the commit message `kubectl krew info rabbitmq` will output the available - not installed - version. In contrast, `kubectl krew list` outputs the installed version.
As explained in `kubectl krew list --help`:
> Remarks:
>  Redirecting the output of this command to a program or file will only print the names of the plugins installed
Therefore, we parse the rabbitmq plugin version from the `krew list` logs by increasing the verbosity to `4`.
If the rabbitmq plugin is not installed via krew, the command will output an appropriate error message.
I wrote the tests such that they don't require `krew` to be installed. If krew isn't …
=> Add 'kubectl rabbitmq version' sub command

controllers/rabbitmqcluster_controller_test.go, internal/resource/configmap.go, internal/resource/configmap_test.go, internal/resource/rabbitmq_plugins.go, internal/resource/rabbitmq_plugins_test.go, internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #442 
-  Stop populate CR labels/annotations to pods. Instance labels and annotations are still populated and updated for statefulSet.
- Stop updating label/annotation on server conf configMap, because updates to server-conf configMap triggers pod restart. Instance labels and annotations are still applied at creation.
Stop updating label/annotation on plugins configmap, because updates to the plugins configMap triggers unnecessary `rabbitmq-plugins set`.
Have run unit, integration, and system tests.
=> Stop triggering pod restarts for CR labels/annotations updates

README.md
Kubernetes 1.16 is out of support and we test in 1.17+
=> Update minimum Kubernetes version

docs/examples/mtls/README.md, docs/examples/mtls/rabbitmq.yaml
- caCertName is now hardcoded as ca.crt
This closes #
```
```
```
```
=> Correct mTLS example

config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
after bumping sigs.k8s.io/controller-tools from v0.4.0 to v0.4.1.
=> Run `make manifests`

system_tests/system_tests.go, system_tests/utils.go
Before this PR, the persistence test wasn't testing persistence.
This PR fixes a regression introduced in https://github.com/rabbitmq/cluster-operator/commit/ca9e12fdbe0492bf6ca7de6405ef644cca5c02be.
=> Make persistence test testing persistence

Makefile, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, hack/crd-patch.json, hack/patch-crd.sh
- new controller-gen now adds default value 'TCP' to ports the hack is no longer needed
Have tried new CRD against 1.18 k8s version and it works.
=> Remove crd patch hack

docs/examples/mtls-inter-node/README.md, docs/examples/mtls-inter-node/inter_node_tls.config, docs/examples/mtls-inter-node/rabbitmq-ca.yaml, docs/examples/mtls-inter-node/rabbitmq-certificate.yaml, docs/examples/mtls-inter-node/rabbitmq.yaml, docs/examples/mtls-inter-node/setup.sh
This example shows how to configure mTLS between RabbitMQ nodes. It uses Cert Manager but could be used without it (secret would have to be created manually).
=> Example: mTLS between RabbitMQ nodes

system_tests/system_tests.go, system_tests/utils.go
Make rabbitmq image configurable by setting environment variables so that we can run system tests using the commercial rabbitmq image as well as using the OSS rabbitmq image.
Next step is to add a Concourse job to run system tests with the commercial image.
=> Make rabbitmq image configurable

api/v1beta1/rabbitmqcluster_types.go, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, controllers/rabbitmqcluster_controller.go, controllers/rabbitmqcluster_controller_test.go, controllers/reconcile_tls.go, controllers/reconcile_tls_test.go, internal/resource/configmap.go, internal/resource/configmap_test.go, internal/resource/service.go, internal/resource/service_test.go, internal/resource/statefulset.go, internal/resource/statefulset_test.go, system_tests/system_tests.go, system_tests/utils.go
This closes #459 
- Add `spec.tls.disableNonTLSListeners` property, when set to true, the operator disables non TLS listeners in given RabbitmqCluster
- ` spec.tls.disableNonTLSListeners` also means tcp readiness probe would use port `amqps` instead of `amqp`
- The property can only configure to true if TLS is enabled, or else there will be errors logged and published to events
- when ` spec.tls.disableNonTLSListeners` set to true, the epmd 4369 and the prometheus 15692 ports remains open on the container level for clustering and for prometheus scraping (neither of them are exposed in the outfacing service object)
- tcp listeners disabled for any enabled plugins as well by setting …
=> Add spec.tls.disableNonTLSListeners property

api/v1beta1/rabbitmqcluster_types.go, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, controllers/rabbitmqcluster_controller_test.go, controllers/reconcile_tls_test.go, internal/resource/configmap.go, internal/resource/configmap_test.go, system_tests/system_tests.go
This closes #482 
- fix a bug where management tcp listener no longer works when tls is enabled and disableNonTLSListeners is set to false
- management tcp listener can be disabled by setting management.ssl.port without setting management.tcp.port
- management.tcp.port is set to 15672 when tls is enabled but disableNonTLSListeners is false
- do not set management.tcp.port when tls is enabled and disableNonTLSListeners is true
- increate timeout in one integration test case( it was flaking due to the short timeout)
I have thought about including `management.tcp.port = 15672` as the default configuration and deleting the key if `disableNonTLSListeners` is set to true. However, that will …
=> Stop disabling management tcp listener when tls enabled

controllers/rabbitmqcluster_controller.go, go.sum
Fixes #472.
The error described in the issue occurred sporadically when updating the RabbitMQ status subresource in https://github.com/rabbitmq/cluster-operator/blob/06a015fa05bf67e2b01777055e3bfdb4cd4ec575/controllers/rabbitmqcluster_controller.go#L126
It occurred when creating a new cluster. It occurred in the 2nd reconcile iteration running very shortly after the 1st reconcile iteration which already updates the status subresource in https://github.com/rabbitmq/cluster-operator/blob/06a015fa05bf67e2b01777055e3bfdb4cd4ec575/controllers/rabbitmqcluster_controller.go#L203
If a conflict occurs when updating the status subresource, I decided to simply requeue the key instead of using `clientretry.RetryOnConflict`. The latter option would be very confusing because the controller would need …
=> Requeue when conflict on status update

internal/resource/configmap_test.go
This closes #464
As suggested by @Zerpet in #464 this commit reuses the cluster generator, to clean up the config map tests.
=> Reuse cluster generator in configmap tests

.github/workflows/stale.yml
This is an action from a team retro or sync up. The modal votes for the threshold were for 60 days to stale, 30 days to close.
PRs & issues can still be marked with the label `never-stale` to be exempt from this check.
=> Lower staleness threshold to 60 days

.github/workflows/pr.yml
This closes #496 
As discussed in standup and sync-up, we should test (kubectl apply with dry run flag) all example manifests in `docs/examples` in PRs to avoid having out-of-date examples documented.
Tested the github action flow locally using [act](https://github.com/nektos/act) and this tool is great and super convenient!
=> Test all examples in PR github action

docs/examples/production-ready/README.md, docs/examples/production-ready/pod-disruption-budget.yaml
`PodDisruptionBudget` for the production-ready example
=> Add `PodDisruptionBudget`

docs/examples/production-ready/rabbitmq.yaml
Ensure all pods of the same RabbitMQ cluster are spread across zones.
As implemented in https://github.com/rabbitmq/cluster-operator/blob/6a15d4bc71c970f4f7ff5f619f3bb21b81bdcdba/internal/resource/statefulset.go#L479-L481
=> Fix topologySpreadConstraints labelSelector

internal/resource/statefulset.go, internal/resource/statefulset_test.go
This fixes issue: https://github.com/rabbitmq/tanzu-cluster-operator/issues/20
- always mount '/var/lib/rabbitmq/' before '/var/lib/rabbitmq/mnesia/' to avoid shadowing; popular open-sourced container runtimes like docker and containerD will sort mounts in alphabetical order to avoid this issue, but there's no guarantee that all container runtime would do so
- update initContainer capabilities to be able to deploy successfully in cluster with ESXi runtime
- Context on the capabilities: dropping all capabilities except CHOWN, DAC_OVERRIDE, and FOWNER. The first of these capabilities is necessary to change a file's owner, the second is necessary to permit chown to traverse directories to …
=> Mounts and capabilities

internal/resource/statefulset.go, internal/resource/statefulset_test.go
Sets the UID on /var/lib/rabbitmq/mnesia/
Clusters fail to start on Rancher 2.5.2 Kubernetes 1.19.3 using vSphere CSI with the following error:
```
Configuring logger redirection
18:25:52.996 [warning] Failed to write PID file "/var/lib/rabbitmq/mnesia/rabbit@hello-world-server-0.hello-world-nodes.default.pid": permission denied
18:25:53.316 [error] Failed to create Ra data directory at '/var/lib/rabbitmq/mnesia/rabbit@hello-world-server-0.hello-world-nodes.default/quorum/rabbit@hello-world-server-0.hello-world-nodes.default', file system operation error: enoent
18:25:53.317 [error] Supervisor ra_sup had child ra_system_sup started with ra_system_sup:start_link() at undefined exit with …
```
=> Fix mnesia permissions in PV

.github/workflows/pr.yml
- Add k8s 1.20 in PR system tests
- Bump to k8s 1.19.1 to the latest 1.19.4
Not removing 1.17 from system tests matrixes just yet since many people are still using older version of k8s and it's not adding any feedback times to our PR workflow since it's parallel anyways
=> Include k8s 1.20 in PR system tests

bin/kubectl-rabbitmq, bin/kubectl-rabbitmq.bats, controllers/rabbitmqcluster_controller.go, controllers/rabbitmqcluster_controller_test.go, controllers/reconcile_rabbitmq_configurations_test.go
This closes #509
This PR is an updated version of PR #511. Updated based on feedback https://github.com/rabbitmq/cluster-operator/pull/511#issuecomment-740023563
- users can set label "rabbitmq.com/pauseReconciliation" to true to signal that they would like to pause reconciliation for this CR
- added helper command: `pause-reconciliation` which adds the label to a cr, `resume-reconciliation` which deletes the label from a cr, and `list-pause-reconciliation-instances` which lists all rabbitmqclusters with the label set to true in the current targeted namespace
- When `Reconcile()` detects the label, it logs, publishes events and sets NoWarnings status condition to false with reason `paused reconciliation`
- Deleting the label, or setting the label to any value other than 'true' will resume …
=> Pause reconciliation label

controllers/reconcile_tls_test.go, go.mod, internal/resource/statefulset.go, internal/resource/statefulset_test.go, system_tests/system_tests.go, system_tests/utils.go
This closes #506 
- secrets and configmaps mounted with subpath do not not get updated in pods when changed, as reported in
issue: https://github.com/kubernetes/kubernetes/issues/50345
- RabbitMQ itself supports TLS credential rotation without restart. By mounting tls secrets without using subpath, rabbitmq pods will pick up cert changes and support tls rotation without server restart.
```
```
For example, for a Kubernetes context …
=> Mount tls secrets using projected volume not subpath

internal/resource/configmap.go, internal/resource/configmap_test.go, internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes https://github.com/rabbitmq/cluster-operator/issues/479
Add TLS support for prometheus
```
```
```
```
=> Add support for  prometheus TLS

docs/examples/production-ready/rabbitmq.yaml
As part of [TGIR S01E09](https://www.youtube.com/watch?v=y2HAJBiXsw0),
we found that the ignore strategy was not ideal for production use cases
where a network partition occurred due to the necessity of manual
intervention.
In addition, the readiness probe does not account for the fact that a
pod is partitioned, meaning that in the case of a 3-node quorum queue cluster with a
2-1 network partition, 1/3 of the traffic will be routed via the Service
to pods that cannot serve traffic due to them not establishing quorum.
By contrast, the pause_minority strategy will stop the RabbitMQ app,
meaning that the Service will no longer redirect traffic to the pod
until it regains quorum.
=> Change prod example to use pause_minority strategy

internal/resource/configmap.go, internal/resource/configmap_test.go
Enable the Prometheus standard port with the TLS deploy
I introduced this problem with this PR https://github.com/rabbitmq/cluster-operator/pull/533 found by @mkuratczyk 
To recap the behaviour:
- standard deploy:
- tls deploy `disableNonTLSListeners=false`
- tls deploy  `disableNonTLSListeners = true`
=> Prometheus fix standard port in TLS deploy

.github/workflows/codeql-analysis.yml
This integrates GitHub's native SAST, CodeQL, into the PR workflow, as well as a periodic scan of the main repo. This allows continuous static analysis of our Go code.
Once this is merged, CodeQL will build up a base profile of the repo, which will be visible in the Security tab in the GitHub repo. Any vulnerabilities will be visible there.
Any PRs that are subsequently merged will also be scanned and compared to this baseline, and any new vulnerabilities added will be flagged in the PR, and the Security tab of the repo.
=> Create GH Actions workflow for CodeQL SAST

docs/examples/prometheus/README.md, docs/examples/prometheus/kube-prometheus-stack-values-tls.yaml.example, docs/examples/prometheus/rabbitmq-podmonitor-tls.yaml
With this PR https://github.com/rabbitmq/cluster-operator/pull/533 it is possible to enable the Prometheus tls endpoint. 
Update the example to show how to use them
=> Add prometheus  tls example

internal/resource/statefulset.go, internal/resource/statefulset_test.go
- PR related to bug reported in issue: #537
-  k8s allows pvc template in sts to not have namespace specified and assumes it's the same namespace as the sts
- operator needs to set namespace because controller reference can only be set when both object name and namespace are specified
=> Always set PVC override namespace to sts namespace

README.md, controllers/rabbitmqcluster_controller_test.go, docs/examples/mtls/README.md, docs/examples/production-ready/README.md, internal/resource/statefulset_test.go, internal/status/status_test.go, system_tests/system_tests.go, system_tests/utils.go
Some small refactors that:
* removes redundant type conversion
* fixes typos
* use SatisfyAll when three or more `Expect` on the same object
=> Small refactors

controllers/rabbitmqcluster_controller.go, controllers/reconcile_cli.go, controllers/reconcile_finalizer.go, controllers/reconcile_rabbitmq_configurations.go, controllers/reconcile_tls.go, controllers/suite_test.go, main.go
Relates to previous PR: #542 
With controller-runtime 0.7, Reconcile() takes a context.Context object with a logger. The logger is pre populated with controller name, gvk, object name and namespace. Operator using this logger reduces redundancy because operator no longer needs to create its own logger and it doesn't need to include rmq name and namespace manually in every single log.
Before this change, a sample log could look like: 
```
2021-01-07T12:46:12.232Z	INFO	rabbitmqcluster-controller	Finished reconciling RabbitmqCluster	{“namespace”: “rabbitmq-system”, “name”: “sample”}
```
After this change, the same log will look like:
```
2021-01-07T16:27:38.661Z	INFO	controller-runtime.manager.controller.rabbitmqcluster	Finished reconciling	{"reconciler group": "rabbitmq.com", "reconciler …
```
=> Use logger from context in Reconcile()

config/default/overlays/dev/manager_image_patch.yaml, config/default/overlays/kind/manager_image_patch.yaml, main.go
Before this PR, the cluster operator always used a hard-coded logger dev mode, even in production.
After this PR, the logger is prod mode by default.
This means from now on, by default, the logger will log at `Info` level and output JSON.
When developing locally deploying the operator using `make deploy-dev` and `make deploy-kind`, the logger will use dev mode.
Furthermore, users can now configure more zap flags (see https://github.com/kubernetes-sigs/controller-runtime/blob/66537ca5b7439b06f2f3b08901640f934834c9a1/pkg/log/zap/zap.go#L227-L233)
For example, they can set the log level as follows:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
...
spec:
...
spec:
containers:
- name: operator
command:
- /manager
args:
- zap-log-level=error
```
This resolves #551.
For more context, …
=> Make logger configurable

controllers/rabbitmqcluster_controller_test.go, internal/resource/configmap.go, internal/resource/configmap_test.go, internal/resource/statefulset.go, internal/resource/statefulset_test.go, system_tests/system_tests.go
Related to #503
- RabbitMQ configurations are placed in conf.d
- RabbitMQ env and advanced config are still placed in the default location.
- The Server conf ConfigMap is specified as its own volume only when advanced config or env configurations are set in the RabbitmqCluster Spec.
- The server configuration is always added to a projected volume.
N/A
- There are changes to all test suites: unit, integration and system
=> Place RabbitMQ configuration in confd

main.go
The new port matches the one listed in https://github.com/prometheus/prometheus/wiki/Default-port-allocations.
=> Change default operator metrics port

internal/resource/configmap_test.go
- RabbitmqConf can be interpreted as rabbitmq.conf which is not what the test asserts on
=> Variable rename 𐬺

.github/workflows/pr.yml, Makefile
This closes #446
- Added new make targets: `make chart-tests`, `make kubectl-plugin-tests`, and `make tests` which runs unit, integration, system, chart, and plugin tests
- Use these new make target in PR workflow
- 
```
```
```
```
=> Make tests 🥑

.github/workflows/pr.yml, README.md, api/v1beta1/rabbitmqcluster_types.go, api/v1beta1/rabbitmqcluster_types_test.go, bin/kubectl-rabbitmq, charts/rabbitmq/Chart.yaml, charts/rabbitmq/example-configurations.yaml, charts/rabbitmq/expected-template-output, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
- Deploy with rmq 3.8.10 by default
- Change PR github action check to test on `3.8.8`, `3.8.9`, and `3.8.10`
=> Deploy with rmq 3.8.10 by default

.github/workflows/publish-versioned-api-ref.yml, .github/workflows/update-latest-api-ref.yml, hack/generate-ordered-api-reference-list.sh
This PR changes the API Reference Doc generation to be more version-aware.
On every push to main:
The 'Latest' version of the Doc will be updated if changed.
On every semantic version tag of the repo:
A new versioned API doc is created, of the name `API_Reference_vx.y.z.asciidoc`.
The Wiki sidebar is regenerated to contain all versions of the API reference, in version order, with Latest at the top.
It's likely easier to see rather than read all of this, so I did a quick demo on the fork used for this PR:
[Example Latest Ref Doc](https://github.com/rabbitmq/cluster-operator/wiki/API_Reference)
[Example Versioned Ref Doc](https://github.com/rabbitmq/cluster-operator/wiki/API_Reference_v1.2. …
=> Add versioning to autogenerated API docs

api/v1beta1/rabbitmqcluster_status.go, api/v1beta1/rabbitmqcluster_status_test.go, api/v1beta1/rabbitmqcluster_types.go
Saw the api package structure from postgres-operator and liked it: https://github.com/pivotal/postgres-for-kubernetes/tree/master/postgres-operator/api/v1
I think a bit separation looks cleaner and will be easier to navigate. No strong opinion here, please disagree if you didn't like this refactor.
=> Separate RabbitmqClusterStatus from rabbitmqcluster_types.go

bin/kubectl-rabbitmq
This closes: #587 
Add a message to remind people to install plugin `tail` in rabbitmq cli plugin help message. I had to Gblame to find the PR to find this particular requirement, not very user friendly.
=> Add help msg to install tail plugin in rabbitmq plugin

bin/kubectl-rabbitmq, bin/kubectl-rabbitmq.bats
You can now use `-n NAMESPACE` in most commands or `-A` in some to list
objects across namespaces.
Note: these flags need to be specified immediately after `kubectl
rabbitmq`. One day we'll probably rewrite the whole plugin in Go and it
will be easier to handle more flexible flag parsing.
This closes #579
=> Add support for -n/-A to select namespace(s)

.github/workflows/pr.yml
There are some JSON files in the examples related to RabbitMQ. Kubectl should not apply those JSON files because they don't contain Kubernetes manifests and would cause a failure in the action.
Related to check errors in #590
=> Test examples action should only apply YAML

controllers/rabbitmqcluster_controller.go, controllers/rabbitmqcluster_controller_test.go, controllers/reconcile_cli.go
When `Reconcilie()` fails to set plugins, feature flags, or rebalance when necessary: 
- publish `failedReconcile` warning events
- set `ReconcileSuccess` to false 
Removed an integration test because pods are never successfully created in envTest and plugins cannot be successfully set, so `ReconcileSuccess` can never be set to true in integration tests. 
All tests passing locally
=> Fail to set plugins (or any other necessary cli commands) should result in ReconcileSuccess set to false

README.md, api/v1beta1/rabbitmqcluster_types.go, api/v1beta1/rabbitmqcluster_types_test.go, bin/kubectl-rabbitmq, charts/rabbitmq/Chart.yaml, charts/rabbitmq/example-configurations.yaml, charts/rabbitmq/expected-template-output, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
This closes #595 
Deploy RMQ 3.8.12 by default.
Should we add a warning in our README to warn people about the maintenance mode data loss issue for mirror queues?
All passing.
=> Deploy RMQ 3.8.12 by default

api/v1beta1/rabbitmqcluster_types.go, docs/api/rabbitmq.com.ref.asciidoc
This is to accommodate the bump to the latest elastic/crd-ref-docs version.
=> Fix API ref docs to include Plugin type description

.github/workflows/publish-versioned-api-ref.yml, .github/workflows/release.yml, .github/workflows/update-latest-api-ref.yml
We don't add the notifications for failed PRs since it would create too much noise in our Slack channel whenever someone opens a PR where tests are failing.
However, let's add notifications when other GitHub actions fail, e.g. failing to update the krew index. This one was unnoticed for a week.
=> Add Slack notifications on failed GitHub actions

config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, controllers/rabbitmqcluster_controller.go, controllers/rabbitmqcluster_controller_test.go, controllers/reconcile_persistence.go, controllers/reconcile_scale_down.go, controllers/reconcile_scale_down_test.go, internal/resource/configmap.go, internal/resource/configmap_test.go, internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #298 
- set `podManagementPolicy` to `Parallel`
- Use cluster_formation.randomized_startup_delay_range to avoid race condition between nodes during initial cluster formation
- This change solves the problem of failing to restart the cluster when all pods are deleted and recreated at once; with podManagementPolicy set to 'OrderedReady', pod 0 is also the first one getting recreated, but it may not be the last node to shut down. This problem was first reported in [community slack](https://rabbitmq.slack.com/archives/CTMSV81HA/p1609882247391800?thread_ts=1609802102.387100&cid=CTMSV81HA)
- **Disallow cluster scale down entirely** After talking to @mkuratczyk @MirahImage …
=> Set Pod Management to 'Parallel' and disallow cluster scale down entirely

README.md, api/v1beta1/rabbitmqcluster_types.go, api/v1beta1/rabbitmqcluster_types_test.go, bin/kubectl-rabbitmq, charts/rabbitmq/Chart.yaml, charts/rabbitmq/example-configurations.yaml, charts/rabbitmq/expected-template-output, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
- Bump default to `3.8.14`
- I modified the help msg from kubectl plugin to refer to `3.8-management` rather than a specific patch version
This can be automated in pipeline 🤷‍♀️
=> Bump default rabbit version to 3.8.14

bin/kubectl-rabbitmq
Use 15672 or 15671 to access Management, based on TLS settings. Previously `kubectl rabbitmq manage TLS-ONLY-INSTANCE` would fail as it would try to port-forward and open 15672 which is not available.
=> Add support for TLS-only instances to `kubectl rabbitmq manage` command

Dockerfile, go.mod
=> Bump golang to 1.16

Makefile
This PR adds a make target to install and remove cert manager deployment. It leverages Helm to install/upgrade/uninstall.
This is useful to install Cert Manager to your current Kubernetes context. Cert Manager is used to generate certificates for TLS related deployments.
```
kind create cluster
make cert-manager
kubectl get pods --all-namespaces
make cert-manager-rm
```
=> Make target to install Cert Manager

.github/workflows/pr.yml, README.md
- Removed end-of-life v1.17
- Updated testing for v1.18 to v1.18.15
- Updated testing for v1.19 to v1.19.7
- Updated testing for v1.20 to v1.20.2
```
```
```
```
=> Update supported tested k8s versions to match kind 0.10.0

docs/examples/production-ready/rabbitmq.yaml
https://www.rabbitmq.com/prometheus.html#prometheus:
> For production systems, we recommend a minimum value of 15s for
> Prometheus scrape interval and a 10000 (10s) value for RabbitMQ's
> collect_statistics_interval. With these values, Prometheus doesn't
> scrape RabbitMQ too frequently, and RabbitMQ doesn't update metrics
> unnecessarily.
The previous `collect_statistics_interval` was `5000` (5 seconds).
=> Increase collect_statistics_interval

Makefile
By default Helm installs CRDs. However the Cert Manager chart is "special" and doesn't
install CRDs unless you set a chart property. This PR adds such option.
```
kind create cluster
make cert-manager
kubectl api-resources
```
=> Install CRDs as part of cert manager make-target

api/v1beta1/rabbitmqcluster_status.go, api/v1beta1/rabbitmqcluster_types.go, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, docs/api/rabbitmq.com.ref.asciidoc
This closes #636 
- remove unused rabbitmqCluster.status.clusterStatus from cluster status
```
```
```
```
=> Remove unused status.clusterStatus

api/v1beta1/rabbitmqcluster_types.go, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
This closes #
Organized kubebuilder markers a bit, it looked a bit messy before.
With this change you can see rabbitmqclusters when doing `kubectl get all`, like
```
❯ k get all
NAME                                             READY   STATUS    RESTARTS   AGE
pod/rabbitmq-cluster-operator-84c7588b78-768tk   1/1     Running   0          13m
pod/sample-server-0                              1/1     Running   0          8m33s
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                          AGE
service/sample         LoadBalancer   10.7.248.214   34.105.166.183   5672:30898/TCP,15672:31213/TCP   8m34s
service/sample-nodes   ClusterIP      None …
```
=> Add RabbitmqClusters to categories all

system_tests/system_test.go, system_tests/utils.go
This closes #
We bumped the version of kubectl installed in our CI image as a side effect of commit: https://github.com/pivotal/rabbitmq-for-kubernetes-ci/commit/6f3d20bd7e44e585b15a75f4f427d4bc3f0156ba
With kubectl 1.21, when running `kubectl exec` withnot providing a container name, there would be an additional line of output which breaks how certain system tests assertions. For example:
```
k exec basic-rabbit-server-0 -- ls
Defaulted container "rabbitmq" out of: rabbitmq, setup-container (init) # additional line compared to previous
bin
boot
dev
etc
```
- related CI failures are here: https://hush-house.pivotal.io/teams/rabbitmq-for-kubernetes/pipelines/operator/jobs/system-tests-oss- …
=> Provide container name in podExec helper function

config/crd/patches/crd_labels_patch.yaml, config/manager/manager.yaml, config/namespace/base/namespace.yaml, config/rbac/leader_election_role.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/role_labels_patch.yaml, observability/prometheus/monitors/README.md, observability/prometheus/monitors/rabbitmq-cluster-operator-podmonitor.yml, observability/prometheus/monitors/rabbitmq-servicemonitor.yml
This sets the component label on resources generated by kustomize to be consistent with the topology operator.
See also https://github.com/rabbitmq/messaging-topology-operator/pull/122
```
```
```
```
=> Update app.kubernetes.io/component labels on resources

internal/resource/configmap.go, internal/resource/configmap_test.go
We've observed cluster formation failures at a rate of about 7%.
With these values, it seems to be below 1% (not a single failure in 100
tests). The ultimate solution remains to implement locking in the k8s
peer discovery plugin but this change should alleviate the issue until
then.
More info: https://github.com/rabbitmq/cluster-operator/issues/662
=> Wider randomized_startup_delay_range

internal/resource/statefulset.go, internal/resource/statefulset_test.go
When TLS is enabled use the prometheus-tls port in the annotation.
This matches the behaviour of the Service:
When TLS is enabled, port 15691 is exposed in the Service.
=> Use Prometheus TLS port if TLS is enabled

bin/kubectl-rabbitmq
New versions of `kubectl` print a warning otherwise.
While at it, simplify enable-all-feature-flags by using the "all" feature introduced in 3.8.10.
=> Explicitly use rabbitmq container in kubectl exec

docs/examples/community-plugins/test.sh, docs/examples/federation-over-tls/test.sh, docs/examples/import-definitions/test.sh, docs/examples/mtls-inter-node/test.sh, docs/examples/multiple-disks/test.sh, docs/examples/tls/test.sh
This closes #
With kubectl 1.19, when running kubectl exec withnot providing a container name, there would be an additional line of output , for example:
```
k exec basic-rabbit-server-0 -- ls
Defaulted container "rabbitmq" out of: rabbitmq, setup-container (init) # additional line compared to previous
bin
boot
dev
etc
```
This broke the test.sh assertion from import-definition example
```
+ ./test.sh
/tmp/tmp.9yG85cM7iO /tmp/build/03d44872/go/src/github.com/rabbitmq/cluster-operator/docs/examples/import-definitions
+ kubectl exec import-definitions-server-0 -- rabbitmqadmin --format=raw_json --vhost=hello-world --username=hello-world --password=hello-world …
```
=> Provide container name for pod exec in test examples

.github/workflows/pr.yml
Bump to latest k8s patch versions for PR workflow.
```
```
```
```
=> Bump to latest k8s patch version for PR workflow

bin/kubectl-rabbitmq
This allows running stream-perf-test easily, for example:
```
kubectl rabbitmq stream-perf-test INSTANCE --rate 100
```
Notes for reviewers: due to yesterday's default port changes, you need to run the Operator from `main` to use port 5552 and a very fresh RabbitMQ image, for example:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
name: stream
spec:
replicas: 1
image: pivotalrabbitmq/rabbitmq-stream
rabbitmq:
additionalPlugins:
- rabbitmq_stream
```
=> New command: stream-perf-test

system_tests/system_test.go
We have been getting timeouts on PVC expansion test in the CI, for example:
- https://hush-house.pivotal.io/teams/rabbitmq-for-kubernetes/pipelines/operator/jobs/system-tests-commercial-image/builds/140
- https://hush-house.pivotal.io/teams/rabbitmq-for-kubernetes/pipelines/operator/jobs/system-tests-commercial-image/builds/135
This PR bumps the timeout from 120s to 180s.
```
```
For example, for a Kubernetes context named …
=> Bump timeout for PVC expansion

internal/resource/configmap.go, internal/resource/configmap_test.go, internal/resource/service.go, internal/resource/service_test.go, internal/resource/statefulset.go, internal/resource/statefulset_test.go
Automatically configure TLS for the Stream plugin when TLS is enabled.
To test, I'd recommend `openssl s_client -connect INSTANCE-nodes.default.svc.cluster.local:5551`.
Integration tests will come later as the client's TLS support is still being worked on.
=> Add support for Stream over TLS

system_tests/system_test.go, system_tests/utils.go
This PR adds a missing expectation that nodes cluster correctly.
The expectation should fail when we hit issue #662.
**Additional context:**
This test also serves as an integration test for the `rabbitmq_peer_discovery_k8s` plugin.
Instead of having an extra integration test suite for `rabbitmq_peer_discovery_k8s` plugin in rabbitmq-server (e.g. as done for the `rabbitmq_peer_discovery_aws` plugin [here](https://github.com/rabbitmq/rabbitmq-server/blob/92173c151436129e688828114d5827fed5413575/deps/rabbitmq_peer_discovery_aws/test/integration_SUITE.erl#L103-L117)), we can integration test this plugin much simpler in the cluster-operator system tests.
=> Test that nodes cluster correctly

go.mod, go.sum
Follow up PR from https://github.com/rabbitmq/cluster-operator/pull/710. The updated sha in #710 is incorrect 🤔
=> Bump github.com/onsi/ginkgo from 1.16.2 to 1.16.3

controllers/rabbitmqcluster_controller.go, controllers/reconcile_tls.go, controllers/reconcile_tls_test.go
- extract a helper function to set `ReconcileSuccess` status condition. We do this for 4 times in our `Reconcile()` func.
- set  `ReconcileSuccess` to false if there is any error from `reconcile_tls()`. I realized that TLS failures in controller was only logging and publishing events, but not setting the status condition. It should! status condition is tested in integration tests.
=> Status refactors

README.md, api/v1beta1/rabbitmqcluster_types.go, api/v1beta1/rabbitmqcluster_types_test.go, charts/rabbitmq/Chart.yaml, charts/rabbitmq/example-configurations.yaml, charts/rabbitmq/expected-template-output, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
This closes #
Bump default RabbitMQ version to `3.8.17` from `3.8.16`
Have run all local tests
=> Bump default to RabbitMQ 3.8.17

api/v1beta1/rabbitmqcluster_types.go, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
This closes #647 
This adds two columns to the output of `kubectl get` for `RabbitmqClusters`: 
- AllReplicasReady
- ReconcileSuccess
These correspond to the equivalent fields in the Status of the object in question.
For example, when creating a 3-node cluster:
Once the deployment is complete:
After applying an update to the cluster:
After applying an update that fails to reconcile (in this case, some override config that was incorrect):
I considered adding system tests for this feature, however decided against it as I believe these tests would be too brittle to changes to kubectl itself, and feels outside the remit of testing for this repo.
Please ensure you run the unit, integration …
=> Add additional printing columns

internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #357 
This changes the init container from running as root to running as the same specified RabbitMQ user - 999. This allows RabbitmqClusters to be deployed on environments with restrictive security policies that do not allow for root containers, while still retaining support for Openshift.
RabbitMQ requires group ownership of the Mnesia database, which is mounted as a persistent volume.
The root init container was added in #303, as a means of changing the GID of this volume on Openshift - in Openshift, we observed that the GID was not being modified by `StatefulSet.Spec.SecurityContext.FSGroup`, and so the volume had the wrong owner. We added the init container to set the …
=> Use RabbitMQ user for init container instead of root

internal/resource/statefulset.go, internal/resource/statefulset_test.go
Currently, the operator was not compatible with the bitnami/rabbitmq container because it requires to run as group `0` (following the Openshift container guidelines https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html). As the library/rabbitmq container only requires to be run as user `999` to work, the runAsGroup setting does not seem to be necessary. 
The changes were tested in minikube and GKE and no issues appeared.
```
```
You will need to target a k8s cluster and have the operator deployed for …
=> Remove runAsGroup to add compatibility with bitnami/rabbitmq

internal/resource/statefulset.go, internal/resource/statefulset_test.go
Removes the undefined variable from the unit tests, and removes the RunAsGroup from the initContainer. Not sure how it made it through #724 without failing there.
```
```
```
```
=> Fix missing definition in failing unit tests

internal/resource/statefulset.go, internal/resource/statefulset_test.go
This is no longer needed as fsGroup modifies this for us.
`fsGroup`, set in the securityContext of mounted volumes, already sets the ownership of files within the volumes, so explicitly setting them in the initContainer is unnecessary. We also no longer run as GID 999, so part of the chown operation is actively doing the wrong thing now.
This brings the operator closer to supporting Openshift's arbitrary user flow. 
Following this PR will be updates to the docs around installing on Openshift.
```
```
You will need to target a k8s …
=> Remove chmod operations from init Container

README.md, api/v1beta1/rabbitmqcluster_types.go, api/v1beta1/rabbitmqcluster_types_test.go, charts/rabbitmq/Chart.yaml, charts/rabbitmq/example-configurations.yaml, charts/rabbitmq/expected-template-output, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
N.B.: This will fail until a 3.8.18-management image is published on Dockerhub.
Bumps the default RabbitMQ image to 3.8.18.
```
```
```
```
=> Set default RabbitMQ image to 3.8.18, containing JIT for Erlang 24

controllers/rabbitmqcluster_controller_test.go, docs/examples/default-security-context/README.md, docs/examples/default-security-context/rabbitmq.yaml, docs/examples/default-security-context/test.sh, internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #741 and closes #746 
If an override is provided with the SecurityContext of either the rabbitmq container or init container set to `{}`, this ensures the resultant STS uses the default securityContext of the container runtime.
Unlike #746, this preserves the validation of override types, rather than failing at reconcile time if a user provides an unknown field.
This only works for securityContext right now; the only other fields I think this affects are:
`topologySpreadConstraints`
`resources`
I don't think they're a high priority to make this work for, but I could add them in if needed.
To …
=> Allow SecurityContext and PodSecurityContext to be reset to default

config/manager/manager.yaml
Removing unnecessary securityContext from manager Pod:
- runAsUser & runAsGroup are already enabled by the `USER` line of the
Dockerfile
- fsGroup is unneeded since the manager mounts no volumes.
The securityContext field overrides some of Openshift's arbitrary user
handling, while providing no benefit to the operator. Removing it
provides the same security guarantees as before, while also making
Openshift installation experience the same as any other Kubernetes
distribution.
```
```
You will need to target a k8s cluster and have …
=> Remove securityContext from manager Deployment

docs/examples/pod-anti-affinity/README.md, docs/examples/pod-anti-affinity/rabbitmq.yaml, docs/examples/production-ready/README.md, docs/examples/production-ready/rabbitmq.yaml
This PR adds `podAntiAffinity` example and modifies the existing procudtion-ready example so that the pods will not be scheduled on the same node. This should ensure higher availability in any Kubernetes cluster.
The pod-anti-affinity example uses `preferredDuringSchedulingIgnoredDuringExecution` type, while production-ready example uses `requiredDuringSchedulingIgnoredDuringExecution` as no production cluster should have potential one point of failure (i.e. one node).
=> Add new podAntiAffinity example and modify existing production-ready example

README.md, api/v1beta1/rabbitmqcluster_types.go, api/v1beta1/rabbitmqcluster_types_test.go, charts/rabbitmq/Chart.yaml, charts/rabbitmq/example-configurations.yaml, charts/rabbitmq/expected-template-output, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
This closes #
Set `3.8.19` as default RMQ image
All passing locally
=> Bump default to `3.8.19`

docs/examples/sidecar/README.md, docs/examples/sidecar/rabbitmq.yaml, docs/examples/sidecar/test.sh
This closes #
Add a sidecar example with test. Suggestion from @yaronp68  😸 
Github action has been very flaky these day. Create a github issue to handle that: https://github.com/rabbitmq/cluster-operator/issues/767
```
```
```
```
=> Add a sidecar example

.github/workflows/pr.yml, system_tests/system_test.go, system_tests/utils.go
This closes #767
1. remove k8s `1.18` from PR system tests workflow (1.18 has reached end of life 3 months ago)
2.  bump timeouts for rabbitmq configurations system tests for two different timeout related flakes that we have been seeing:
1)`pluginsUpdatedAt` annotation should be removed after updates (timeout bumped from 60s to 120s)
```
Timed out after 60.003s.
plugins ConfigMap annotation should have been removed
Expected
<map[string]string | len:1>: {
"rabbitmq.com/pluginsUpdatedAt": "2021-07-19T09:00:20Z",
}
not to have key
<string>: rabbitmq.com/pluginsUpdatedAt
```
2)`mqtt` port should be added to default user secret after `rabbitmq_mqtt` plugin is enabled (timeout bumped from 1s …
=> Bump system tests timeouts and remove k8s 1.18 from PR workflow

.github/workflows/pr.yml, system_tests/system_test.go, system_tests/utils.go
Another PR to fix system tests timeout issue with PR workflow. Also removes k8s `1.19` and `1.20` from PR workflow. 
The team had a discussion about github action and CI pipeline test coverage, we decided on:
1. only test on k8s 1.21 in github action; remove k8s 1.19 and 1.20 from the system tests matrices (considering 1.21 is not available in GCP yet)
2. test on k8s 1.19 in CI pipeline (no 1.20 coverage considering it’s unlikely to have compatibility issue that only breaks on 1.20 but not 1.19 or 1.21)
3. PR github workflow will run system tests on 5 different rabbitmq versions: 3.8.8, latest 3.8, latest 3.9, rabbitmq-server master with OTP 23 and rabbitmq-server master with OTP 24)
3. …
=> Bump timeouts for mqtt connection system tests, remove k8s 1.19 and 1.20 tests from PR workflow

internal/resource/default_user_secret.go, internal/resource/default_user_secret_test.go
Cluster name is configurable and not fixed.
This is related to #75 and [Messaging Topology Operator issue 186](https://github.com/rabbitmq/messaging-topology-operator/issues/186)
Removes hardcoded `.cluster.local` suffix from the service address in the `host` field of the default-user secret.
=> Remove `.cluster.local` from host in default-user secret.

.github/workflows/pr.yml
Test PR against stable 3.9 instead of rc image.
```
```
```
```
=> Test PR against stable 3.9 instead of rc image

bin/kubectl-rabbitmq
This closes #801 
The command `open` is specific to MacOS. Linux desktops use `xdg-open` instead. The rest of the script should be compatible with Linux.
N/A
No tests added or modified.
=> Adapt instance manage to support Linux

README.md, api/v1beta1/rabbitmqcluster_types.go, api/v1beta1/rabbitmqcluster_types_test.go, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, system_tests/system_test.go, system_tests/utils.go
This closes #
Bump default RMQ image to `3.8.21`. Will squash before merging.
```
```
```
```
=> Bump default rmq image to 3.8.21

Makefile
MacOS requires users to allow/deny whenever an unknown process attempts to listen on a TCP port.
Since `make run` always generates a new binary, it is necessary to always accept/deny the attempt.
By only listening on the loopback address, we can avoid the prompt
=> Avoid MacOS firewall warning on `make run`

controllers/reconcile_no_persistence_test.go, controllers/reconcile_persistence.go, internal/resource/statefulset.go, internal/resource/statefulset_test.go
For test environments, especially in CI/CD, it may be beneficial to skip
creating the PVC altogether since the whole cluster is disposable
anyway. With this change, if spec.persistence.storage is set to 0, the
PVC is not created and an `emptyDir` volume is used instead. Changing from
0 to anything else is not supported (and doesn't make much sense
anyway).
This closes #776
=> Don't create PVC if spec.persistence.storage==0

controllers/reconcile_scale_down.go, controllers/reconcile_scale_down_test.go
This closes #758
Adds extra detail to the warning generated when attempting to scale down the cluster. The log now states the number of replicas is marked as current, and the desired number of replicas that were used to calculate whether a scale down was occurring. This should help debug other race conditions as demonstrated in #758 .
Example status:
```
```
```
$ kubectx …
```
=> Add extra logging and event detail when attempting to scale down cluster

internal/resource/default_user_secret.go, internal/resource/default_user_secret_test.go, internal/resource/erlang_cookie_test.go
This closes #
- this change will make it easier to specify exclusion rules whenusing schema sync plugin
- After this change, an example username and password could look like:
```
username: default_user_mDj_Yp58qvSynGbUEC3
password: AbdFbGnu2HaVAIkJ1W1AUq42uVglXW1E
```
Generated username and password logic is tested in unit test level.
=> Prefix generated username with 'default_user_'

controllers/rabbitmqcluster_controller.go, controllers/reconcile_persistence.go, controllers/reconcile_persistence_test.go, controllers/suite_test.go, internal/scaling/scaling.go, internal/scaling/scaling_suite_test.go, internal/scaling/scaling_test.go
This allows for this section of the code to have its own test suite,
without relying on the restrictions placed by envtest. This allows us to
test more scenarios, such as where a controller has previously crashed
and left the existing API objects in a bad state (e.g. statefulsets
missing, PVCs being the wrong size, etc.).
This also fixes #782, as the process of scaling PVCs should now be more
idempotent than before:
- StatefulSets don't need to be present on the cluster in order to scale
the PVCs (as long as the PVCs exist)
- PVC scaling is done on a PVC-by-PVC case, rather than all at once, so
that if one or more replicas have already scaled their PVCs it does not
block the others
- The …
=> Make PVC scaling more idempotent & resilient to crashes

docs/examples/network-policies/README.md, docs/examples/network-policies/allow-inter-node-traffic.yaml, docs/examples/network-policies/allow-operator-traffic.yaml, docs/examples/network-policies/allow-rabbitmq-traffic.yaml, docs/examples/network-policies/rabbitmq.yaml
This closes #835 
[NetworkPolicies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) allow users to restrict the source/destination of ingress/egress traffic of their Pods. This documented example demonstrates the kinds of traffic a user may wish to restrict/allow on their cluster.
You can enable the network plugin on GKE for testing with:
```
gcloud container clusters create CLUSTER_NAME --enable-network-policy
```
```
```
You will need to target a k8s cluster and have the operator deployed for running …
=> Add documented examples for NetworkPolicies

controllers/reconcile_cli.go, controllers/reconcile_tls.go, internal/scaling/scaling.go
As reported [here](https://groups.google.com/g/rabbitmq-users/c/TdRHEh4pzug/m/KXJ7Nm_SAgAJ), we should not log debug messages such as info level.
As described in https://github.com/go-logr/zapr#increasing-verbosity:
> logr's [...] V(1) is zap's DebugLevel (which is numerically -1).
=> Decrease log volume by making use of debug level

docs/examples/production-ready/README.md
I expect this to preempt some follow-up questions which I have seen come up a few times already. I encourage others to answer follow-up questions in the same way. It will save us from repeating the same answers, and sharing what we know to be true.
If you think that there is too much information in this README, we can split the questions into a separate file. I think that approach will fragment the information and make it less accessible, but I am open to what others feel would work better.
=> Answer some production-ready questions that came up in private threads

controllers/rabbitmqcluster_controller.go, controllers/reconcile_tls.go, controllers/reconcile_tls_test.go
This closes #884
- do not requeue on error when `disableNonTLSListen` is set to true but TLS is not enabled; this is a user configuration error and need to be fixed by user updating rabbitmqcluster manifest which will trigger reconcile anyways
- `reconcileTLS()` returns a special error `disableNonTLSConfigErr`. `Reconcile()` identifies the error and exit the reconcile so no k8s resource is created for the misconfigured rabbitmqcluster.
=> Do not requeue error when disableNonTLSListen is misconfigured

system_tests/system_test.go, system_tests/utils.go
This fixes #863 (WIP)
The issues that i identified were mainly these ones:
- Persistent volume operations such as volume expansion take far longer than initially expected. The timeout used is 10m which should be long enough. But the reality is that sometimes it takes longer.  I wonder if it makes sense to get the PVC's events before aborting the test case so that we can know what has happened to the PVC up this point. For the time being, I have added a logging statement that logs the PVC's `status.conditions`. 
- Test cases that checked ConfigMap's annotation `rabbitmq.com/pluginsUpdatedAt` were very time sensitive. I managed to reproduce it a few times so it seemed that 30 seconds timeout was too tight. We could ramp it up to 1 minute without any issues. The next timeout would be …
=> Fix system tests

controllers/rabbitmqcluster_controller_test.go, internal/resource/service.go, internal/resource/service_test.go
This closes #878 
- Added field `appProtocol` to Service Ports, to enable Istio protocol detection
- FLAKE in integration test
By setting this field, we are able to take full advantage of all Istio traffic monitoring features and rich metrics, we must hint Istio what's the underlying protocol. [Source
here](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/).
According to Kubernetes docs, protocol that are not registered in IANA registry as well-known ports, must use a suffix, like `my.company.com/my-protocol`. Surprisingly, STOMP does not have a well-known port assigned.
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numb …
=> Include protocol information in Service ports

internal/resource/service.go, internal/resource/service_test.go
MQTT/STOMP over TLS, and its web socket variants, can be exposed together over TLS, they are not mutually exclusive. Previously, we were not exposing MQTT/STOMP over TLS, if mTLS was enabled, but replacing them with the web socket variants.
Integration test `the service annotations are updated` may flake. This flake will be improved by #888 
```
```
```
$ …
```
=> Fix port exposure in MQTT/STOMP and WS variants

go.mod, go.sum, tools/tools.go
Because it is no longer used. The team uses other debuggers, everyone have a different flavour.
[skip ci]
=> Remove delve from tools

internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #
Detailed context in issue: https://github.com/rabbitmq/opportunities/issues/156
Openshift expects containers to be able to run with arbitrary user ids. Their recommendation is for all files that processes need to access during runtime, give permission to the root group and the Openshift random users are all from the root group.
```
```
```
$ …
```
=> Set podSecurityContext.fsGroup to 0 instead of 999

bin/kubectl-rabbitmq, bin/kubectl-rabbitmq.bats
Deploys perf-test and stream-perf-test as Kubernetes Jobs, rather than running pods directly.
This is designed to make clean-up easier.
=> kubectl rabbitmq perf test improvements

README.md
This closes #930 
Kubernetes 1.18 is no longer supported by the operator, as of v1.11.0. This is due to the feature gate `ServiceAppProtocol` being disabled by default in 1.18; the feature is needed by the RabbitmqCluster service.
Note: I also edited the v1.11.0 release notes to document the drop of support.
```
```
```
$ make …
```
=> Document lack of 1.18 support

controllers/rabbitmqcluster_controller.go
commit "5f98b43" added the ability to set image pull secrets from the
DEFAULT_IMAGE_PULL_SECRETS env var. 
https://github.com/rabbitmq/cluster-operator/commit/5f98b4304fbee6153cbf6b4f9ccb9255993f08de
In the case where the `DEFAULT_IMAGE_PULL_SECRETS` env var is unset, `DefaultImagePullSecrets` will be `""`, and `strings.Split(r.DefaultImagePullSecrets, ",")` will return an array of length one containing an empty string and an image pull secret will be created with an empty string. This commit adds check to the output of `strings.Split()` to ensure we don't set an empty strings.
When this empty string is saved and parsed by k8s, resulting operations get this error:
```
$ kubectl rollout restart statefulset/rabbitmq-cluster-server
error: statefulsets.apps "rabbitmq-cluster-server" map: …
```
=> fix: don't set empty image pull secrets

Makefile, config/ytt/overlay-manager-image.yaml
This will be used in the pipeline to publish to additional registries.
Related [#869]
Make sure you have `ytt` installed, then run:
```bash
kustomize build config/installation/ | ytt -f- -f config/ytt/overlay-manager-image.yaml \
--data-value operator_image=quay.io/bunny:latest
```
Observe the image of the Operator Deployment is set to `quay.io/bunny:latest`.
Edit: tag correct issue 🙈
=> Helper overlay to patch the Operator image

docs/examples/vault-default-user/setup.sh
The older chart is not compatible with K8s 1.21, which is used in our system tests. Tested on the CI cluster and it works now.
```
```
```
```
=> Bump vault chart version to fix CI

docs/examples/multiple-disks/test.sh
The 'grep' command in the test had incorrectly escaped quote characters.
```
```
```
```
=> Fix multiple disks documented example test

.github/workflows/pr.yml, Makefile, bin/kubectl-rabbitmq, bin/kubectl-rabbitmq.bats
The test to set debug logs was broken since the default image became
3.9.x because this commit: https://github.com/rabbitmq/rabbitmq-server/commit/cdcf602749a34674d9eb285df1e31fe9c4aebb89
changed the debug log prefix from `debug` to `dbug`.
There's a small tweak to the make target that runs the kubectl bats
tests locally to include the repo's bin first in the path. This is
important because the version installed by krew will take precedence.
The above also allows us to simplify slightly the PR workflow file and
run everything using `make`.
```
kind create cluster
kubectl rabbitmq install-cluster-operator
make kubectl-plugin-tests
```
=> Update kubectl-bats tests

main.go
Bump user default updater image to latest patch.
The latest user updater image is built with Golang 1.17.7 and latest dependency bumps.
```
```
=> Update default user updater image to latest patch

observability/quickstart.sh
Bump the version of the kube-prometheus helm chart to be compatible with recent Kubernetes versions, when deployed with the quickstart script.
```
```
```
```
=> Bump kube-prometheus stack to 31.0.2

main.go
Set the LogSink for the klog logger used by client-go to the same as the controller-runtime zap logger
See https://github.com/rabbitmq/messaging-topology-operator/issues/295#issuecomment-1060631658
=> Ensure consistent log formats

Makefile, main.go
easy way to get client config
This closes #
```
```
```
```
=> change way to get client config

Makefile, controllers/suite_test.go, docs/api/rabbitmq.com.ref.asciidoc
Due to changes in graceful signal handling in testenv, our tests timeout
to teardown testenv and cause an afterSuite failure. The workaround is
to cancel the context in the manager to avoid waiting for pending
requests in the API server.
Check the discussion in https://github.com/kubernetes-sigs/controller-runtime/issues/1571 about the problem.
Changes to integration tests. Unit and system tests are unaffected.
=> Update envtest to use latest available 1.22

controllers/reconcile_persistence.go, docs/examples/README.md, docs/examples/vault-default-user/README.md, internal/metadata/annotation_test.go, internal/scaling/scaling.go, internal/scaling/scaling_suite_test.go, internal/scaling/scaling_test.go
This closes #1025 
[Error string shouldn't be capitalized](https://github.com/rabbitmq/cluster-operator/commit/96b476249013beb0fc0be05721ed719aed70a986)
[Remove unused param from generatePVCTemplate](https://github.com/rabbitmq/cluster-operator/commit/89d90cc8d4438298745f2f6ecddbf75219202cfa)
[Document examples namespace in vault example and examples README](https://github.com/rabbitmq/cluster-operator/commit/8b3b56e05d87ccc451dc936980db423d5022fadd)
=> Document `examples` namespace in examples and small refactors

.github/workflows/pr.yml, README.md, bin/kubectl-rabbitmq.bats, main.go
Note that the default format of how the log level is printed changed from Docker image 3.9.13 (default image before this PR) to 3.9.14 due to the changes in https://github.com/docker-library/rabbitmq/commit/3e8f0f18ac6a823f2a95d92e67ca88fd95186386
3.9.13:
```
2022-05-11 22:08:22.370896+00:00 [warn] <0.644.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": rebuilding indices from scratch
```
3.9.14:
```
2022-05-11 22:09:26.666086+00:00 [warning] <0.644.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": rebuilding indices from scratch
```
=> Bump default RabbitMQ image to v3.10.1

controllers/rabbitmqcluster_controller.go, controllers/reconcile_status.go, controllers/reconcile_status_test.go
This closes #1030
- Set status.defaultUser.serviceReference when vault default user is used; this is because downstream, topology operator
in this case, may rely on the rabbitmqcluster.status for certain information. topology operator relies on the service
reference to get the name of the ingress service to be able to connect to a given rabbitmqcluster
- Small refactor to move logic that updates status.defaultUser and status.binding into one function so it's cleaner in Reconcile()
- Rename updateStatus() to updateStatusConditions(); the function updates statusConditions instead
of the entire object status
Status tested in integration test.
=> Vault svc reference

observability/prometheus/monitors/README.md, observability/prometheus/monitors/rabbitmq-servicemonitor.yml
This closes #1007 
Instead of adding a new example yaml, the tls section is added as comment section since the rest of the configuration is the same.
=> Document how to set up tls verify for prometheus servicemonitor

config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
This closes #
Re generate manifests after k8s api and controller tools updates
=> Generate manifests with k8s 1.24 and controller-gen 0.9

internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #1049 
Remove legacy prometheus scrape annotations of statefulset / pod
All tests have passed successfully. 
```
$  make unit-tests integration-tests
go mod download
grep _ tools/tools.go | awk -F '"' '{print $2}' | xargs -t go install
go install github.com/elastic/crd-ref-docs github.com/mikefarah/yq/v4 github.com/onsi/ginkgo/v2/ginkgo github.com/sclevine/yj sigs.k8s.io/controller-runtime/tools/setup-envtest sigs.k8s.io/controller-tools/cmd/controller-gen sigs.k8s.io/kind sigs.k8s.io/kustomize/kustomize/v4
crd-ref-docs \
--source-path ./api/v1beta1 \
--config ./docs/api/autogen/config.yaml \
--templates-dir ./docs/api/autogen/templates \
--output-path ./docs/api/rabbitmq.com.ref.asciidoc \
--max-depth 30
2022-06-01T11:08:10.068+0200    INFO    crd-ref-docs    Loading …
```
=> remove prom scrape annotation

controllers/reconcile_cli.go, controllers/reconcile_finalizer.go, controllers/utils.go, internal/resource/configmap.go, internal/resource/default_user_secret.go, internal/resource/erlang_cookie.go, internal/resource/headless_service.go, internal/resource/rabbitmq_plugins.go, internal/resource/role.go, internal/resource/role_binding.go, internal/resource/service.go, internal/resource/service_account.go, internal/resource/statefulset.go, system_tests/utils.go
This closes #
```
```
```
``` 
Wrap all error
=> Wrap all error

Dockerfile, Makefile, main.go, pkg/profiling/pprof.go, pkg/profiling/pprof_test.go, pkg/profiling/profiling_suite_test.go
Allow users to opt-in to exposing pprof debugging endpoints on the operator's metrics port.
Users may add the `ENABLE_DEBUG_PPROF` env variable to the operator Pod to enable the pprof endpoints.
This is an opt-in pattern, as memory/CPU profiling can have a non-insignificant impact on runtime perf,
and could be a denial of service vector. These endpoints should not be enabled in production.
With this feature enabled, users can access the pprof output at `<OPERATOR_URL>:<METRICS_PORT>/debug/pprof`. For example, after
port-forwarding to the operator Pod:
```
go tool pprof -inuse_space -web http://localhost:9782/debug/pprof/heap
```
For more info on pprof: …
=> Add pprof debug endpoint

.github/workflows/pr.yml
Update PR workflow to run on latest available Kubernetes version in KinD.
Given that we support the latest k8s version since we merged #1044 and Kubernetes 1.21 is out of support since 1.24 became GA, we should update our workflow to test on a newer Kubernetes version.
Edit: 100% I will squash merge
N/A change to GitHub Actions.
=> Update PR workflow with latest k8s

controllers/rabbitmqcluster_controller.go, controllers/reconcile_operator_defaults.go, controllers/reconcile_operator_defaults_test.go
- extract operator defaults to a separate func to keep Reconciler shorter and more concise
- extract operator defaults controller tests to dedicated test unit as well
- use updateRabbitmqCluster() since the update logic is shared for updating these operator defaults
Tested in integration controller tests suite
=> Extract operator defaults to a separate func

.github/workflows/operatorhub.yml
=> Adding a workflow to create a PR to k8s-operatorhub/community-operators

config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
This closes #
Update crd after k8s api and controller-gen bump. We haven't regenerated the CRD after recent k8s api bump to 1.24.
=> Update crd after k8s api and controller-gen bump

controllers/reconcile_rabbitmq_configurations_test.go, internal/resource/service_test.go, internal/resource/statefulset_test.go
This closes #
- new feature added in ginkgo V2; using entry description for table tests descriptions that can be easily formatted
- some of our table tests descriptions are quite complicated so I didn't replaced those
- see ginkgo doc: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#new-table-level-entry-descriptions
=> Use EntryDescription for DescribeTable tests

.github/workflows/pr.yml, README.md
This closes #
Stop testing rmq 3.8 as it has reached end of support
- remove 3.8.8 github action tests
- update README to say the Operator supports 3.9 onwards
=> Stop testing rmq 3.8

.github/workflows/pr.yml, controllers/reconcile_cli.go, controllers/reconcile_cli_test.go, internal/resource/configmap.go, internal/resource/configmap_test.go
Since we dropped support for RabbitMQ 3.8 in https://github.com/rabbitmq/cluster-operator/pull/1110, we can now simplify the cluster-operator:
1. Remove deprecated `cluster_formation.randomized_startup_delay_range` configurations such that warning `[warn] <0.130.0> cluster_formation.randomized_startup_delay_range.min and cluster_formation.randomized_startup_delay_range.max are deprecated` won't be output anymore in RabbitMQ logs. See https://github.com/rabbitmq/rabbitmq-server/pull/3075.
2. Use `rabbitmqctl enable_feature_flag all` command introduced by @mkuratczyk and @michaelklishin in https://github.com/rabbitmq/rabbitmq-server/commit/ce655864050a78f46005b8aa5e047394a6178cd6.
=> Remove RabbitMQ 3.8 support

.github/workflows/pr.yml, README.md, internal/resource/configmap.go, internal/resource/configmap_test.go
This closes #
- set `cluster_formation.target_cluster_size_hint`. The property is currently used in importing definitions: https://github.com/rabbitmq/rabbitmq-server/pull/3981
- update github action to test again `3.9.9` and README
- There needs to be release notes added when next operator version is cut as this is explicitly changing the minimal support RMQ version (RMQ without this configuration will fail to deploy).
=> Set cluster size hint

docs/examples/json-log/rabbitmq.yaml
Removes the image restriction on the JSON logging example, since all supported versions of RabbitMQ are now valid for this particular documented example.
The CI testing this example was failing since the image 3.9.4-management is no longer compatible with the operator.
```
```
```
```
=> Remove version restriction on JSON-log example

.github/release.yml
Added dependabot to the list of excluded authors for the sake of generating release notes.
Once I know this is working, I will add this also to the other operators.
```
```
```
```
=> Exclude dependabot from auto-generated release notes

.github/workflows/pr.yml, Dockerfile, go.mod
=> Bump golang to 1.19

.github/workflows/pr.yml, Makefile
* Add `vuln` target to makefile to run govulncheck
* Run `vuln` target as part of test and build targets
=> Add govulncheck to makefile.

.github/workflows/operatorhub.yml
=> Fixing .yaml to .yml bug on operatorhub pipeline

config/rbac/service_binding_cluster_role.yaml
This automatically sets up the RBAC required to work with implementors of the Service Binding specification.
As per the spec recommendation:
> Cluster operators and CRD authors SHOULD opt-in resources to expose provisioned services by defining a ClusterRole with a label matching servicebinding.io/controller=true
From https://servicebinding.io/spec/core/1.0.0/#considerations-for-role-based-access-control-rbac
This closes #1149 
Adds a new ClusterRole with the appropriate `servicebinding.io/controller=true` label.  The default `kustomize` configuration appends `rabbitmq-cluster-` to the resource name.
=> Add Aggregating ClusterRole for Service Bindings

.github/workflows/codeql-analysis.yml, .github/workflows/operatorhub.yml, .github/workflows/pr.yml, .github/workflows/prometheus-rules.yml, .github/workflows/publish-versioned-api-ref.yml
v2 actions are deprecated and produce warnings due to outdated nodeJS version.
=> Bump github action dependencies

.github/workflows/pr.yml
Same in topology operator https://github.com/rabbitmq/messaging-topology-operator/pull/487
Use latest go patch in github action. This will make `govulncheck` less likely to fail.
=> Use latest go patch in github action

.github/workflows/build-test-publish.yml, .github/workflows/release.yml
- Sets baseline release to 2.1.0
-  This is the most recent release that triggered a rolling restart
- Fixes the kubectl rabbitmq release job for krew
```
```
```
```
=> Post-2.1.0 pipeline fixes

api/v1beta1/rabbitmqcluster_types.go, controllers/rabbitmqcluster_controller.go, controllers/reconcile_operator_defaults.go, controllers/suite_test.go, main.go
Part of #1003 
Add experimental ENV to let rabbitmq operator update images. **No safety checks at the moment.**
```
```
```
```
=> let rabbitmq operator to control images

.github/workflows/build-test-publish.yml
=> generating single-arch image on main needed for carvel-dev pipeline

README.md, main.go
This closes #
Bump default RMQ version when `spec.image` is not set from `3.10.2` to  latest `3.11.x`. 
```
```
```
```
=> Bump default RMQ version

.github/workflows/build-test-publish.yml
=> test to let carvel pipeline to work

config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, controllers/rabbitmqcluster_controller.go, controllers/reconcile_cli.go
- Update generated CRD
- log cluster spec at debug instead of info
- log message about requeue request to enable plugin at debug instead of info
- log successfully queue rebalance like other cli command
'Start reconciling' log which used to contain `.spec` now looks like
`2023-02-21T17:35:40Z	INFO	Start reconciling	{"controller": "rabbitmqcluster", "controllerGroup": "rabbitmq.com", "controllerKind": "RabbitmqCluster", "RabbitmqCluster": {"name":"sample","namespace":"rabbitmq-system"}, "namespace": "rabbitmq-system", "name": "sample", "reconcileID": "b8013f6d-40a3-45db-9b57-77e21e56d2a2"}`
=> Move verbose log lines to debug

api/v1beta1/rabbitmqcluster_types.go, internal/resource/service_test.go, internal/resource/statefulset_test.go, main.go
This closes #
Open stream port when stream management plugin is on because `rabbitmq_stream_management` turns on `rabbitmq_stream` automatically.
=> Open stream port when stream management plugin is on

README.md, main.go
=> bump default rabbitmq to 3.11.10-management

.github/workflows/build-test-publish.yml
This contributes to https://github.com/rabbitmq/service-operator-experience/issues/164
Workflow is updated to also build and publish single-arch `arm64` image.
Currently the workflow builds and publishes multi-arch (amd64/arm64) and single-arch (amd64) images.
=> Generate arm64 image

observability/prometheus/rules/rabbitmq/low-disk-watermark-predicted.yml
This closes #
The current alert rule for the `LowDiskWatermarkPredicted` can cause an error due to `multiple matches for labels: grouping labels must ensure unique matches`.
If the join is done on both the `pod` and the `instance` that fixes the issue.
The full error log from Prometheus:
```logfmt
ts=2023-03-14T15:17:25.487Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-kube-prometheus-prometheus-rulefiles-0/rabbitmq-rabbitmq-alerting-rules-2acff1e4-8959-4af2-bd88-725641ae175d.yaml group=rabbitmq name=LowDiskWatermarkPredicted index=1 msg="Evaluating rule failed" rule="alert: LowDiskWatermarkPredicted\nexpr: …
```
=> fixed the LowDiskWatermarkPredicted Alert

.github/workflows/build-test-publish.yml
`1.26` kind image has been out for a while now. Lets test on a later version of k8s in github actions.
```
```
```
```
=> Bump k8s version in github actions

main.go
Allows scoping the cache namespace to more than 1 namespace if `OPERATOR_SCOPE_NAMESPACE` is a comma delimited list.
If someone needed to configure their RBAC with non-cluster `roles` and `rolebindings` they would be unable to run the operator. This project requires access to a lot of resources and not everyone's security stance allows for using `clusterroles`. 
Without providing `OPERATOR_SCOPE_NAMESPACE` and using `role` instead of `clusterrole` you get errors such as 
```
failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:rabbit:rabbit-cluster-operator" cannot list resource "configmaps" in API group "" at the cluster scope
```
and a similar error if a …
=> Allow multi namespace cache scoping

observability/grafana/dashboards/erlang-distribution.yml, observability/grafana/dashboards/erlang-distributions-compare.yml, observability/grafana/dashboards/erlang-memory-allocators.yml, observability/grafana/dashboards/rabbitmq-overview.yml, observability/grafana/dashboards/rabbitmq-queue.yml, observability/grafana/dashboards/rabbitmq-quorum-queues-raft.yml, observability/grafana/dashboards/rabbitmq-stream.yml
This closes #1334
Use a perma-link to Grafana Dashboards in rabbitmq-server repo.
`Grafana.com` is rejecting HTTP requests with basic authentication. Earlier, it used to ignore the basic auth, and simply serve the request. This new behaviour in Grafana API breaks the [sidecar import feature of Grafana's Helm Chart](https://artifacthub.io/packages/helm/grafana/grafana#sidecar-for-dashboards). The sidecar from Grafana uses basic authentication in their HTTP request. It then gets a not-authorized response from Grafana API, and dashboard importing fails.
GitHub raw URLs ignore the basic auth and simply serve the file as a static element.
N/A - no code changes
Edit: formatting
=> Update Grafana dashboards

.github/workflows/build-test-publish.yml
Previously -amd64 and -arm64 images were created with tags sha-amd64 and sha-arm64.
For our carvel-pipeline to work properly is convinient to have images tagged with version-amd64 and version-arm64 (ex 2.2.0-amd64 and 2.2.0-arm64 when a new release happens).
Also:
type=semver,pattern={{major}}.{{minor}}
type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
seems not necessary as these created tags of type 2.2 and 2
for example https://hub.docker.com/r/rabbitmqoperator/cluster-operator/tags?page=1&name=2.2 
I have tested these modifications cloning the repo https://github.com/DanielePalaia/cluster-operator/blob/main/.github/workflows/build-test-publish.yml and using my dockerhub account:
https://hub.docker.com/repository/docker/danielepalaia/cluster-operator/g …
=> On new release generate -amd64 and -arm64 release versions

docs/examples/import-definitions/rabbitmq.yaml
This example should make it easier to understand how to mount a definitions file and load its contents.
=> Simplify import-definitions example

docs/examples/community-plugins/rabbitmq.yaml
This may fix #1352
Tried to fix enabling community plugins, downloaded via init-containers. 
Changed `PLUGIN_DIR` to `RABBITMQ_PLUGIN_DIR` and added the default path of shipped plugins to its value. 
```
```
```
[~]$ kubectl exec -ti rabbitmq-server-0 -- bash
Defaulted container "rabbitmq" out of: rabbitmq, copy-community-plugins (init), setup-container (init)
I have no …
```
=> fixed paths and env variable name for plugings

README.md, main.go
=> updating default RabbitMQ image to 3.11.18

system_tests/system_test.go
This should fix the failing tests.
There is no significant difference in how much memory is used with OTP26, but for some reason, we hit the alarm. I think it's fair to just assign more.
=> Assign 700MB to each node

config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, main.go
Bumping rmq version to next rabbitmq commercial version
```
```
```
```
=> bump rmq version

README.md
=> update README doc with correct default rmq version

config/crd/kustomization.yaml, config/default/overlays/dev/kustomization.yaml, config/default/overlays/kind/kustomization.yaml, config/rbac/kustomization.yaml
Hello. I can't use this repo kustomize templates, because "patches:" notation was obsolete. I get errors, when try to execute kustomize:
```
error: invalid Kustomization: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch
```
Could you merge this little PR to fix it?
=> Renamed patches -> patchesStrategicMerge

docs/examples/network-policies/allow-inter-node-traffic.yaml
This closes https://github.com/rabbitmq/cluster-operator/issues/1457
Add missing ports for stream replication to networkpolicies example.
=> feat(docs): add stream ports to inter-node-traffic network-policy

.github/workflows/build-test-publish.yml
Forks do not copy over repo secrets. This step requires a repo secret, and it will fail if the action is triggered from a fork.
=> Exclude Google Auth in PRs

bin/kubectl-rabbitmq
Without the fix, passing `--image-pull-secret` would lead to validation failure.
=> imagePullSecrets is an array

.github/workflows/build-test-publish.yml
v5 of this action generates artifacts with manifest containing `unknown` OS and architecture.
=> Reverting docker/build-push-action version

system_tests/system_test.go
This will allow us to run the system-tests in a different namespace than the default "rabbitmq-system"
=> removing encoded rabbitmq-system namespace in system-tests

.github/workflows/build-test-publish.yml, README.md, bin/kubectl-rabbitmq.bats, main.go
Bump the default to 3.13.1. Do not mention some old RMQ and Kubernetes versions that likely work, but we surely don't test new Operator versions with them
=> Deploy 3.13 by default

.github/workflows/testing_and_publishing_OLM_bundle.yml
Small fix on test_and_publish_OLM_bundle action workflow.
There is a small issue during the last release: 
https://github.com/rabbitmq/cluster-operator/actions/runs/8539313818/job/23393756084
Basically the sh shell doesn't recognize properly the line:
BUNDLE_VERSION=${BUNDLE_VERSION:1}
giving a bad substitution error.
This should fix this issue.
This PR is also bumping GO to 1.22 and golang.org/x/net to v0.23.0 in order to avoid the new vulnerability issue detected in https://github.com/rabbitmq/cluster-operator/actions/runs/8552381205/job/23433359006
It is also adding some missing crd fields to our CRD after a make manifests.
It maybe related to  https://github.com/rabbitmq/cluster-operator/commit/be674d6b3e5632ccd335360ee87821eaeea0e828
=> small fix on test_and_publish_OLM_bundle

config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
The cluster operator crd is currently not updated. 
make manifests is adding the pkiRootPath field. 
This was probably a step missing in:
https://github.com/rabbitmq/cluster-operator/commit/be674d6b3e5632ccd335360ee87821eaeea0e828
=> updating cluster operator crd

controllers/reconcile_rabbitmq_configurations.go, controllers/reconcile_rabbitmq_configurations_test.go, internal/resource/configmap.go, internal/resource/configmap_test.go
=> Don't restart the cluster after scale-out

docs/design/20200520-graceful-pod-termination.md, internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #1595
Previously all actions in preStop hook were performed independently of each other. For example, drain would kick in even if queue sinchronization returned an error. This resulted in cases where graceful shutdown was assumed just because last action in the script, i.e. `rabbitmq-upgrade drain`, is a success.
Now all actions in the hook actually waits for the previous action to complete successfully. The only exception is checking for the deletion marker file. Script will still exit with 0 (and shutdown will continue) if the marker is present without executing other actions.
I'm not familiar with Go and I don't have development environment to test these changes, sorry. This is just a friendly PR from a fellow sys admin. I'm also not sure if ampersands in Go strings need to …
=> Fix graceful shutdown

.github/workflows/build-test-publish.yml
Version 5 of docker/build-push-action produces `unknown` architecture and os in manifest
=> Revert docker/build-push-action version due to known issue

.github/workflows/testing_and_publishing_OLM_bundle.yml
Similarly to: https://github.com/rabbitmq/cluster-operator/pull/1603
This is solving a small issue happening in the last released (changing shell to bash), plus a small correction in the way we compute the replace field operator to solve:
https://github.com/rabbitmq/cluster-operator/actions/runs/9056466175
=> small fix on testing_and_publishing_OLM_bundle action

docs/examples/production-ready/rabbitmq.yaml
This fixes the datatype of the resource attributes in the production ready example. Otherwise this example will cause CD tools like Flux, to constantly update the resource and change it back to a numeric value.
Since the `production-ready` example is rather prominently mentioned in the docs, I think it might make sense to provide an example that doesn't trigger changes by CD tools (even though using a numeric is allowed).
=> force string for resource attributes in examples

api/v1beta1/rabbitmqcluster_types.go, internal/resource/statefulset.go, internal/resource/statefulset_test.go
When the annotation rabbitmq.com/disable-default-topology-spread-constraints is set to "true", the default topologySpreadConstraints based on label topology.kubernetes.io/zone is omitted.
As  @Zerpet suggested in issue #1687, I added the annotation to skip the default topology constraint configuration because the override was not working as expected ( #1690 ), and @mkuratczyk was not satisfied with the behavior.
This closes #1687
**Note to reviewers:** Remember to look at the commits in this PR and consider if they can be squashed
When a user adds the annotation  `rabbitmq.com/disable-default-topology-spread-constraints: "true"` in their RabbitMQCluster custom resource, the default topology spread constraint is omitted.
Please ensure you run the unit, integration and system tests before …
=> Add rabbitmq.com/disable-default-topology-spread-constraints annotation

internal/resource/configmap.go, internal/resource/configmap_test.go
See https://github.com/rabbitmq/rabbitmq-server/pull/11999 for full context.
Starting with RabbitMQ 4.0, anonymous login should be disabled in production.
`anonymous_login_user` and `anonymous_login_pass` both default to `guest` in RabbitMQ 4.0. The rabbitmq/cluster-operator complies already with best practices by provisioning a new `default_user` and `default_pass` instead of using RabbitMQ's default `guest` user.
Instead of having RabbitMQ advertise the ANONYMOUS mechanism, this commit disables anonymous logins.
Because `anonymous_login_user` is a new RabbitMQ 4.0 `rabbitmq.conf` setting and the cluster-operator doesn't know what RabbitMQ version it deploys and setting `rabbitmq.conf` key `anonymous_login_user` in RabbitMQ 3.13 would make booting RabbitMQ fail, this commit modifies the …
=> Disable ANONYMOUS login

api/v1beta1/rabbitmqcluster_types.go, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
A maximum string lenth of 2,000 was too restrictive. The new limit of 100,000 matches the limit of `advancedConfig`.
Resolves #1707
=> Increase max length of additionalConfig

Dockerfile
Github actions for docker build have been emitting warnings about deprecated docker syntax.
=> Fix docker syntax warnings from github actions.

docs/examples/production-ready/rabbitmq.yaml, system_tests/system_test.go
This setting is not used anymore in CQ v2.
Relates https://github.com/rabbitmq/rabbitmq-server/pull/12140
=> Remove vm_memory_high_watermark_paging_ratio

.github/workflows/testing_and_publishing_OLM_bundle.yml, Makefile, scripts/print-tag-version.bash
Fix OLM workflow. It was depending on a container image in GCP. This image is not available anymore. This PR
removes that dependency.
=> Fix OLM workflow

internal/resource/default_user_secret.go, internal/resource/default_user_secret_test.go
This closes #1722
Added a new key `connection_string` to the default_user secret with a formatted connection_string.
=> Add connection_string secret to default_user secret

.github/workflows/build-test-publish.yml
* Uploading to GCS is not required anymore
* Removed commented code
* Remove unnecessary permissions
=> Update build test workflow

api/v1beta1/rabbitmqcluster_types.go, api/v1beta1/rabbitmqcluster_types_test.go, controllers/rabbitmqcluster_controller.go, controllers/reconcile_tls.go, internal/resource/default_user_secret_test.go, internal/resource/erlang_cookie_test.go, internal/resource/rabbitmq_plugins_test.go, internal/resource/rabbitmq_resource_builder_test.go, internal/resource/role_binding_test.go, internal/resource/role_test.go, internal/resource/service_account_test.go, internal/resource/service_test.go, internal/resource/statefulset_test.go, internal/scaling/scaling_suite_test.go, internal/scaling/scaling_test.go, system_tests/utils_test.go
This closes #
- **Fix linter errors**
- **Unexport functions in scaling test suite**
The linter is [staticcheck](https://staticcheck.dev/), latest version at this time 2024.1.1. The errors reported were:
- Duplicated imports
- Variables shadowing a package name
=> Fix linter errors

internal/resource/statefulset.go, internal/resource/statefulset_test.go
RabbitMQ 4.0 doesn't include the mirroring-specific command `rabbitmq-upgrade await_online_synchronized_mirror`. Therefore, the preStop hook would fail on 4.0, leading to the maintenance mode not getting enabled at all (the moment a command fails in preStop, the shutdown process continues as if preStop completed).
This approach should make the Operator compatible with 3.x and 4.x.
This closes #1734
=> Ignore mirroring related shutdown errors

api/v1beta1/rabbitmqcluster_types.go, controllers/reconcile_tls.go, controllers/reconcile_tls_test.go, docs/api/rabbitmq.com.ref.asciidoc, internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #1616
- **Remove ineffective test**
- **Fix CA certs overriding server certs**
- **Regenerate API docs**
More information and repro steps in #1616
Unit and integration tests are passing.
=> Fix CA certs overriding server certs

docs/examples/import-multiple-definition-files/README.md, docs/examples/import-multiple-definition-files/definitions.json, docs/examples/import-multiple-definition-files/rabbitmq.yaml, docs/examples/import-multiple-definition-files/setup.sh, docs/examples/import-multiple-definition-files/test.sh, docs/examples/import-multiple-definition-files/users.json
Implements the solution to this question: https://github.com/rabbitmq/cluster-operator/discussions/1801
=> Example of importing from a ConfigMap and a Secret

.github/workflows/testing_and_publishing_OLM_bundle.yml
This closes #
Looks like a small issue in the manifest path passed to poetry during the second execution.
The action with this modification is passing:
https://github.com/rabbitmq/cluster-operator/actions/runs/12909404544
```
```
```
```
=> Fix olm action

.github/workflows/testing_and_publishing_OLM_bundle.yml
This closes #
This should solve the automation problem for the OLM publication.
In case of operatorhub.io we still need to specify the replaces/skip fields in case of operatorhub marketplace we need to avoid these fields. Otherwise the redhat checks will fail
See also: https://github.com/rabbitmq/OLM-Package-Repo/issues/26
These modifications were tested.
```
```
```
$ kubectx …
```
=> adding back replaces field on operatorhub publication

observability/prometheus/rules/rabbitmq/cluster-alarms.yml
This closes #1822
Add a PrometheusRule with 3 alerts, one for each for the rabbitmq cluster alarm states.
Tested in a local cluster, with my setup I get:
```
[FIRING: 1]
Alerts Firing:
- MemoryAlarm: RabbitMQ cluster rabbitmq memory alarm active. Publishers are blocked.
```
=> PrometheusRule for rabbitmq alarm states

observability/prometheus/rules/rabbitmq/cluster-alarms.yml, observability/prometheus/rules/rabbitmq/container-restarts.yml, observability/prometheus/rules/rabbitmq/file-descriptors-near-limit.yml, observability/prometheus/rules/rabbitmq/high-connection-churn.yml, observability/prometheus/rules/rabbitmq/insufficient-established-erlang-distribution-links.yml, observability/prometheus/rules/rabbitmq/low-disk-watermark-predicted.yml
This closes #1855 
If the same `rabbitmq_identity_info` (same pod, same cluster, etc.) is exported twice, only one of the values is used.
When using the default ServiceMonitor from https://github.com/rabbitmq/cluster-operator/blob/main/observability/prometheus/monitors/rabbitmq-servicemonitor.yml, multiple Metrics-Endpoints are scraped that partly return the same value.
It can be tested by applying the files to a test-cluster:
```
- https://raw.githubusercontent.com/mmueller-rs/cluster-operator/fix-prometheus-rules-for-duplicate-metrics/observability/prometheus/rules/rabbitmq/cluster-alarms.yml
- https://raw.githubusercontent.com/mmueller-rs/cluster-operator/fix-prometheus-rules-for-dupli …
```
=> configure rules to merge rabbitmq_identity_info

internal/resource/statefulset.go, internal/resource/statefulset_test.go
It'd be great to get some feedback from users who changed the default init container resources - what did you change them to? I've tested successfully deployed RabbitMQ with a `50Mi` init container using:
* `rabbitmq:4.1-management`
* `bitnami/rabbitmq:4.1`
* `rabbitmq.packages.broadcom.com/vmware-tanzu-rabbitmq:4.1.0`
Given that an init container failure would be a terrible user experience, I'd rather have some headroom, hence `64Mi`.
When originally developed, it wasn't clear what would need to be done in the init container. With hindsight, there's very little to do and the init phase hasn't changed in a long time.
We also assumed that the resources requested for the init container would effectively be reused by the actual `rabbitmq` container later. Turns out that's not the case: …
=> PROPOSAL: Reduce init container memory from 500Mi to 64Mi

controllers/rabbitmqcluster_controller_test.go, controllers/reconcile_finalizer.go, controllers/reconcile_no_persistence_test.go, controllers/reconcile_tls_test.go
There were 3 issues:
* the STS could get deleted before deletion label propagated, leading to some pods terminating for a long time, because they didn't skip quorum checks
* there was an unnecessary explicit STS deletion
* addRabbitmqDeletionLabel was not filtering by namespace, potentially performing operations on wrong/too many pods (if there were multiple clusters with the same name in different namespaces)
=> Improve cluster deletion

api/v1beta1/rabbitmqcluster_types.go, controllers/rabbitmqcluster_controller.go, controllers/reconcile_cli.go, controllers/reconcile_cli_test.go, controllers/reconcile_finalizer.go, controllers/reconcile_operator_defaults.go, controllers/reconcile_rabbitmq_configurations.go, controllers/utils.go, internal/resource/configmap_test.go, internal/resource/default_user_secret.go, internal/resource/default_user_secret_test.go, internal/resource/rabbitmq_resource_builder.go, internal/resource/statefulset.go, internal/scaling/scaling.go, internal/scaling/scaling_suite_test.go, pkg/profiling/pprof_test.go, pkg/profiling/profiling_suite_test.go, system_tests/utils_test.go
A vast majority of these changes were performed automatically by `modernize -fix -test ./...` (
https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize) and  `golangci-lint run --fix`.
=> Modernize the codebase

docs/api/rabbitmq.com.ref.asciidoc
This closes N/A
Documentation update to include the default value of `delayStartSeconds` (ie: value if not set)
N/A - documentation only change.
=> Include default delayStartSeconds value in documentation

api/v1beta1/rabbitmqcluster_types.go, config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml, controllers/reconcile_cli.go, controllers/reconcile_cli_test.go, docs/api/rabbitmq.com.ref.asciidoc
If the cluster definition contains:
```
spec:
autoEnableAllFeatureFlags: true
```
then after each cluster restart, the Operator will call `rabbitmqctl enable_feature_flag all`, which enables all stable feature flags. The property is `false` by default, so this feature is opt-in.
Resolves https://github.com/rabbitmq/cluster-operator/issues/1240
=> Optionally enable all feature flags automatically

README.md, main.go
Deploy RabbitMQ 4.1.1 by default
=> Deploy RabbitMQ 4.1.1 by default

.github/dependabot.yml
Add dependabot groups to combine PRs.
Reduces the number of PRs and eliminates merge conflicts and dependabot rebasing.
=> Add dependabot groups.

config/manager/manager.yaml, internal/resource/statefulset.go, internal/resource/statefulset_test.go
This closes #1910 and #1960 
Adds a securityContext to the cluster operator deployment context. 
Adds securityContext to RabbitMQ Pods, containers, and init containers.
=> Add security context

docs/examples/network-policies/allow-inter-node-traffic.yaml
We have Kubernetes 1.32 currently i think nearly nobody is on Kubernetes 1.21 and lower - i would like to propose to reflect this in the docs.
=> set endPort as default in the netpols examples
