- .github/ISSUE_TEMPLATE/config.yaml
Recommend to ask questions in either RabbitMQ Discussions or in the mailing list.
> Config for GitHub issues

- docs/examples/community-plugins/README.md
- docs/examples/community-plugins/rabbitmq.yaml
> community plugin example

- controllers/rabbitmqcluster_controller.go
* Add secret name to events
* remove useless fmt.Sprintf
* remove unused method
> Some small refactorings

- config/manager/kustomization.yaml
Rather than asking users  in the installation guide) to set these values, let's just have them as defaults
> Set the expected kustomize defaults

- api/v1beta1/rabbitmqcluster_types.go
- controllers/rabbitmqcluster_controller.go
- internal/metadata/label.go
- internal/resource/erlang_cookie.go
- internal/resource/statefulset.go
- internal/status/all_replicas_ready.go
- internal/status/cluster_available.go
- internal/status/no_warnings.go
- internal/status/reconcile_success.go
- internal/status/status.go
Some small changes improving readability and complying with Go conventions.
Look at the individual commits when reviewing.
> Some refactoring

- dependabot.yml
This closes #253
Adds dependabot config to keep dependencies automatically updated.
> Add dependabot config.

- internal/status/all_replicas_ready.go
- internal/status/all_replicas_ready_test.go
> Fix condition AllReplicasReady

- README.md
- version_guidelines.md
This closes #265
```
```
```
```
> Guidelines for non-strict semver (#265)

- README.md
- version_guidelines.md
> Minor edits to the readme and versioning guidelines

- controllers/rabbitmqcluster_controller.go
> Use new helper controllerutil.ContainsFinalizer

- api/v1beta1/rabbitmqcluster_types.go
- api/v1beta1/rabbitmqcluster_types_test.go
- controllers/rabbitmqcluster_controller.go
- internal/metadata/metadata_suite_test.go
- internal/resource/client_service.go
- internal/resource/client_service_test.go
- internal/resource/statefulset_test.go
- internal/status/status_test.go
- system_tests/system_tests.go
- system_tests/utils.go
Small changes
Have run unit tests and integration tests
> Small refactor

- api/v1beta1/rabbitmqcluster_types.go
- controllers/rabbitmqcluster_controller_test.go
- internal/resource/client_service.go
- internal/resource/statefulset.go
- internal/status/status_test.go
- system_tests/system_tests.go
- system_tests/utils.go
Some small cleaning ups. Nothing major.
> Refactorings

- config/installation/kustomization.yaml
As part of #338, we changed the registry reference in *most* places. This PR cahnges the reference in the installation kustomization file to generate the correct version.
> Update registry reference in installation manifest

- system_tests/utils.go
MQTT/STOMP test case has failed multiple times in the CI due to network errors.
Running this test manually passes consistently. Adding a retry logic to the connect
step should eliminate test errors due to random network errors.
Run system tests locally in a GKE cluster. Passes consistently.
> Retry logic to MQTT/STOMP test case suite

- Makefile
- config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
Set `maxDescLen` to 0 to reduce `RabbitmqCluster` CRD by ~70%.
Before:
```
$ wc -c config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
612569 config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
```
After:
```
$ wc -c config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
192377 config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
```
Closes #368
> set `maxDescLen` to 0 to remove descriptions

- system_tests/system_tests.go
- system_tests/utils.go
This closes #
Small changes. Mostly deleting unnecessary code
> System tests refactors

- controllers/rabbitmqcluster_controller.go
- internal/resource/admin_secret.go
- internal/resource/admin_secret_test.go
- internal/resource/configmap.go
- internal/resource/configmap_test.go
- internal/resource/erlang_cookie.go
- internal/resource/erlang_cookie_test.go
- internal/resource/headless_service.go
- internal/resource/headless_service_test.go
- internal/resource/rabbitmq_plugins.go
- internal/resource/rabbitmq_plugins_test.go
- internal/resource/role.go
- internal/resource/role_binding.go
- internal/resource/role_binding_test.go
- internal/resource/role_test.go
- internal/resource/service_account.go
- internal/resource/service_account_test.go
- Remove unnecessary requeue
- Set controller reference in builders rather than the controller loop
Both of which were marked as `TODO` for couple months already 😆
> Controller refactors

- internal/resource/admin_secret.go
Check the error returned by `WriteTo()` function in Admin Secret.
Unit tests are passing ✅
> Check returned error by WriteTo

- README.md
- api/v1beta1/rabbitmqcluster_types.go
- api/v1beta1/rabbitmqcluster_types_test.go
- bin/kubectl-rabbitmq
- charts/rabbitmq/Chart.yaml
> Update rabbitmq to 3.8.9

- api/v1beta1/rabbitmqcluster_types.go
- api/v1beta1/rabbitmqcluster_types_test.go
- controllers/rabbitmqcluster_controller_test.go
> Omit replicas from encoding when empty

- internal/resource/statefulset.go
That's how we call it in the service
> Rename port 15672 to "management"

- .github/workflows/pr.yml
- bin/kubectl-rabbitmq
- bin/kubectl-rabbitmq.bats
> Add tests for kubectl plugin

- bin/kubectl-rabbitmq
- hack/rabbitmq.yaml
New command to tail logs from all nodes.
> Add `kubectl rabbitmq tail` subcommand

- charts/tsmgr/bind.yaml
We've changed the name of the service in https://github.com/rabbitmq/cluster-operator/issues/415
> Update service name in the binding

- .github/ISSUE_TEMPLATE/bug_report.md
Collect cloud provider info in bug report template. This will be useful.
> Collect cloud provider info in bug report template

- README.md
This closes #468 
Remove beta related wording from README.
> Remove Beta from README

- controllers/suite_test.go
- as shown in kubebuilder book https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html
All tests passed locally.
> Simplify controller tests setup 🥑 ⭐ 

- hack/add-notice-to-yaml.sh
- hack/generate-ordered-api-reference-list.sh
Shellcheck suggested a few minor improvements to bash scripts
> Minor bash improvements suggested by shellcheck.

- .github/workflows/pr.yml
- Makefile
- go.mod
- go.sum
- internal/resource/service.go
- internal/resource/service_test.go
- internal/resource/statefulset.go
- internal/resource/statefulset_test.go
- system_tests/system_test.go
- system_tests/utils.go
per conversation with @gerhard 
Add the stream port: `5551` when the stream plugin is enabled.
> Add port for stream plugin

- internal/resource/service.go
- internal/resource/service_test.go
- internal/resource/statefulset.go
- internal/resource/statefulset_test.go
We've decided to change the default port for streams from 5551 to 5552
for consistency with other protocols. 5551 will be used for TLS connections
> Update streams port to 5552

- docs/examples/set-login-password-username/README.md
- docs/examples/set-login-password-username/rabbitmq.yaml
Hi I had added a sample to descript how to set the default account and password in the rabbitMQ cluster in k8s
> add set-login-password-usernam sample

- controllers/rabbitmqcluster_controller.go
This closes #
change switch case simple!
```
```
```
```
> switch case change simple!

- .github/workflows/pr.yml
The image tags have been updated, this updates the tags we use in our PR pipelines.
> Update PR test image tags.

- .github/workflows/build-test-publish.yml
This closes #
Reverting PR #1241 for testing
```
```
```
```
> reverting pr_1241

- api/v1beta1/rabbitmqcluster_types_test.go
- controllers/rabbitmqcluster_controller_test.go
- controllers/reconcile_cli_test.go
- controllers/reconcile_no_persistence_test.go
- controllers/reconcile_persistence_test.go
- controllers/reconcile_scale_down_test.go
- controllers/reconcile_tls_test.go
- internal/resource/configmap_test.go
- internal/resource/statefulset.go
- internal/resource/statefulset_test.go
- system_tests/system_test.go
> Remove deprecated methods

- .github/workflows/build-test-publish.yml
- .github/workflows/prometheus-rules.yml
- Dockerfile
- go.mod
> Use golang 1.20

- docs/examples/priority-class/README.md
- docs/examples/priority-class/priority-class.yaml
- docs/examples/priority-class/rabbitmq.yaml
- docs/examples/priority-class/setup.sh
- docs/examples/priority-class/test.sh
Related #1389 
Add priority class example and its test
> Add priority class example and its test

- .github/workflows/build-test-publish.yml
https://github.com/docker/build-push-action/issues/820
> Reverting docker/build-push-action version bump due to a known issue

- .github/workflows/testing_and_publishing_OLM_bundle.yml
Some modifications in order to integrate: https://github.com/rabbitmq/OLM-Package-Repo/pull/14 now using poetry.
Plus fixed a bug on "replace" version field
> updating olm action to integrate new olm script

- README.md
- main.go
> Bump RabbitMQ to 3.13.2

- config/crd/kustomization.yaml
- config/default/overlays/dev/kustomization.yaml
- config/default/overlays/kind/kustomization.yaml
- config/rbac/kustomization.yaml
This closes #1548
Fixes generated by
```shell
kustomize edit fix
kustomize edit fix --vars
```
> Replace deprecated `patchesStrategicMerge` with v1beta1 `patches`.

- README.md
- main.go
> Default to RabbitMQ 3.13.6

- README.md
- main.go
> Default to RabbitMQ 3.13.7

- README.md
- main.go
> Default to RabbitMQ 4.0.3

- README.md
- main.go
> Default to RabbitMQ 4.0.4

- README.md
- main.go
> Default to RabbitMQ 4.0.5

- README.md
- main.go
Default to rabbitmq:4.1.0-management
> Default to rabbitmq:4.1.0-management
